### ISSUE TITLE
 [paddlets] [ERROR] ValueError: attr: shape doesn't exist!

### ISSUE THREAD

**Issue by pk5557367** [PaddlePaddle/PaddleTS#101]
import paddlets
from paddlets.datasets.repository import get_dataset, dataset_list

print(paddlets.__version__)
0.1.0

print(f"built-in datasets:{dataset_list()}")
built-in datasets:['UNI_WTH', 'ETTh1', 'ETTm1', 'ECL', 'WTH']

dataset = get_dataset('WTH')
执行到 dataset = get_dataset('WTH') 这行时提示
[2022-08-11 14:07:44,459] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!
[2022-08-11 14:07:44,487] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!

**Comment by tongbaiming** [comment]
用spyder 的variable explorer 会有问题，勾选excluded unsupported data types 会消失
