### ISSUE TITLE
PaddleTS 是否支持时序数据的聚类？

### ISSUE THREAD

**Issue by ArcherShirou** [PaddlePaddle/PaddleTS#103]
您好，请教一个问题，现在有一系列无标签的时序数据，也不清楚这些数据有几个类别，请问PaddleTS是否有模型能够对这样的数据进行聚类？是否有相关的示例代码？

**Comment by a10210532** [comment]
目前版本的PaddleTS只支持处理时序预测的问题~
在后续的迭代计划中，我们会陆续加入时序表征、时序异常检测等功能的支持~

对于时序聚类的问题，虽然目前还暂无支持计划，但是因为目前PaddleTS处于高速迭代的期间，我们也会在后续的版本中考虑对这类问题的支持~
