### ISSUE TITLE
不支持paddle版本为2.3.1

### ISSUE THREAD

**Issue by qthui6** [PaddlePaddle/PaddleTS#106]
之前使用过飞浆的cv和nlp，偶然看到发布的paddlets，可实现对时间序列的预测，刚好未来有这方面的需求，马上来体验下！
运行mlp.fit(train_dataset, val_dataset)报错：
ValueError: only the following paddle versions are supported: {'2.2.0', '2.3.0'}, current paddle version: 2.3.1

**Comment by LinWencong** [comment]
一个很好的问题，我们尽快在接下来的版本修复；@kehuo 可以同步一下修复计划😁

**Comment by a10210532** [comment]
目前已经在paddlets 0.1.1版本中解决了这个问题，可以用pip或者源码下载0.1.1版本的代码
