### ISSUE TITLE
设置的协变量是observed_cov_cols，但是报错known_cov长度不够。

### ISSUE THREAD

**Issue by Nefefilibata** [PaddlePaddle/PaddleTS#111]
报错具体信息：ValueError: known_cov length is too short to build known_cov chunk feature. 
                    It needs at least 1 extra Timestamps after known_timeseries.time_index[6:]
数据集构建：
custom_dataset = TSDataset.load_from_dataframe(
    result,  #Also can be path to the CSV file
    time_col='time',
    target_cols=['A'	,'B'	,'C'],
    freq='1d',
    observed_cov_cols='D',
    fill_missing_dates=True,
    fillna_method='zero' #max, min, avg, median, pre, back, zero
)
custom_dataset.plot()

**Comment by a10210532** [comment]
数据在进入模型训练之前，是否经过了其他的特征生成以及转换算子？如TimeFeatureGenerator算子？以为像TimeFeatureGenerator算子会生成known_cov的协变量，如果使用方法不对，有可能会在入模的时候出现上述的报错
可以贴一下完整的代码，方便分析原因

**Comment by Nefefilibata** [comment]
我并没有用算子去构造known_cov协变量，构建完数据集直接将数据送给nhits模型，之后读取文件，在构造的验证集上predict出错。
train_dataset, val_test_dataset = custom_dataset.split(0.8)
val_dataset, test_dataset = val_test_dataset.split(0.8)
train_dataset.plot(add_data=[val_dataset,test_dataset], labels=['Val', 'Test']


from paddlets.models.dl.paddlepaddle import NHiTSModel
nhits = NHiTSModel(in_chunk_len=7, out_chunk_len=1,max_epochs=6000,patience=1000,optimizer_params={'learning_rate': 0.0022})

nhits.fit(train_dataset,val_test_dataset)

val_dataset = TSDataset.load_from_dataframe（
结果，#Also可以是CSV文件的
路径time_col='time'，
target_cols=['A'，'B'，'C']，
freq='1d'，
observed_cov_cols='D'，
fill_missing_dates=True，
fillna_method='zero'#max，min，avg，median，pre，back，zero
）
model.predict(val_dataset )
这或许是一个bug

**Comment by Nefefilibata** [comment]
我并没有用算子去构造known_cov协变量，构建完数据集直接将数据送给nhits模型，之后读取文件，在构造的验证集上predict出错。
train_dataset, val_test_dataset = custom_dataset.split(0.8)
val_dataset, test_dataset = val_test_dataset.split(0.8)
train_dataset.plot(add_data=[val_dataset,test_dataset], labels=['Val', 'Test']


from paddlets.models.dl.paddlepaddle import NHiTSModel
nhits = NHiTSModel(in_chunk_len=7, out_chunk_len=1,max_epochs=6000,patience=1000,optimizer_params={'learning_rate': 0.0022})

nhits.fit(train_dataset,val_test_dataset)

val_dataset = TSDataset.load_from_dataframe（
结果，#Also可以是CSV文件的
路径time_col='time'，
target_cols=['A'，'B'，'C']，
freq='1d'，
observed_cov_cols='D'，
fill_missing_dates=True，
fillna_method='zero'#max，min，avg，median，pre，back，zero
）
model.predict(val_dataset )
这或许是一个bug

**Comment by Nefefilibata** [comment]
验证集构造时把协变量设置错了

**Comment by a10210532** [comment]
辛苦打印一下 val_dataset.columns 和val_dataset 本身，然后把结果截个图看一下~
