### ISSUE TITLE
代码注释存在笔误

### ISSUE THREAD

**Issue by 2Bear** [PaddlePaddle/PaddleTS#235]
[ml_base.py](https://github.com/PaddlePaddle/PaddleTS/blob/main/paddlets/models/forecasting/ml/ml_base.py) 

第101行：

`# b.modelname = "a"`

应该是：

`# b.modelname = "b"`

我提交了[PR](https://github.com/PaddlePaddle/PaddleTS/pull/234)。

**Comment by a10210532** [comment]
感谢提交，已经通过并合入~
