### ISSUE TITLE
多时序数据导入，如何添加其他static_cov_cols变量

### ISSUE THREAD

**Issue by pvalue31415936** [PaddlePaddle/PaddleTS#236]
1、问题询问：多时序数据导入时，无法加入其他static_cov_cols变量，因为TSDataset.load中限制了len(np.unique(df[col])) != 1
2、报错信息：raise_if( col not in df.columns or len(np.unique(df[col])) != 1,"static cov cals data is not in columns or schema is not right!")
3、截图示范：见下图
<img width="839" alt="image" src="https://user-images.githubusercontent.com/25128883/200454956-4af7dc2f-82b0-441b-a243-6e1262846120.png">

_Originally posted by @pvalue31415936 in https://github.com/PaddlePaddle/PaddleTS/issues/110#issuecomment-1306505402_

**Comment by a10210532** [comment]
1：static变量有两种加入方法，第一种在load的时候导入，第二种在构建完成tsdataset之后，手动设置static的值
2：如果想在 load的时候导入static变量，需要满足两个条件
（1）static_col对应的列 存在 在样本中
（2）样本中的static列 在样本中同一个group_id的序列里面是常量
也就是：col not in df.columns or len(np.unique(df[col])) != 1 这个判断条件
可以先基于这两个提交看一下数据是否满足~
