### ISSUE TITLE
load模型失败

### ISSUE THREAD

**Issue by tendrillion** [PaddlePaddle/PaddleTS#244]
ubuntu 20.04 
paddlets 1.0.1
##########################################################################################

ts2vec_params = {"segment_size": 200,
             "repr_dims": 320,
             "batch_size": 32,
             "sampling_stride": 200,
             "max_epochs": 20}
model = ReprForecasting(in_chunk_len=200,
                        out_chunk_len=24,
                        sampling_stride=1,
                        repr_model=TS2Vec,
                        repr_model_params=ts2vec_params)
model.fit(train_data)
model.save("/weights/models1")
model=load("/weights/models1")

发生异常: ValueError
path must be a file path, not a directory: /home/kylin/pythondevelop/paddle_tutorial/ts/trade/weights/models1

**Comment by QGN123** [comment]
表征模型需要用自己的单独的load函数
model =  ReprForecasting.load("/weights/models1")

**Comment by QGN123** [comment]
fixed in https://github.com/PaddlePaddle/PaddleTS/pull/246
