### ISSUE TITLE
概率预测模型报错 No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

### ISSUE THREAD

**Issue by mutou12** [PaddlePaddle/PaddleTS#254]
`from paddlets.utils import backtest
q_loss, quantiles = backtest(data=ts_test_scaled,
     model=deepar,
     start="2013-11-01 00:00:00",
     metric=QuantileLoss([0.1, 0.5, 0.9]),
     predict_window=24,
     stride=24,
     return_predicts=True
)`

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

**Comment by QGN123** [comment]
已知问题，参考https://github.com/PaddlePaddle/PaddleTS/issues/232， 将于1.0.2版本修复
