### ISSUE TITLE
几个建议

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/PaddleTS#258]
1.支持目标变量分类,先实现所有模型和算法,单目标变量分类功能,再实现多目标变量都是整型数的功能,再实现多目标变量有的是整形术,有的是浮点数的功能.
2.支持单机多卡GPU训练,能支持分布式训练就更好了,但是单机多卡训练是最重要的,很多人没钱买机器,租用八卡3090ti进行训练,真心爽歪歪.对于paddlets来说,如果已经选定模型,设置好超参数,或许不用太多GPU资源,但是如果刚开始一个项目,所有模型都要测试一遍,甚至超参数都要多测试,单机多卡GPU训练是很重要的,一个模型训练1天,测试一遍所有模型+超参数那就是一个月的事情了,慢啊.
3.支持C++推理,我指的是,使用VS2022,C++20标准写代码,能准确运行程序.当然了,支持CUDA,OPENCL也是需求之一,这样做可以大幅度提高训练和推理的速度吧.AMD的显卡没什么需求,算了吧,真没想到,谁会买AMD显卡.
4.在ai studio加点项目或案例
5.能不能弄个大数据集.
6.我之前花时间,看了paddlets所有文档,没看代码.给我的感觉就是,预测目标变量的未来值,基本依靠目标变量的过去值,协变量只是起到辅助作用,如果目标变量的未来值,就是靠协变量预测,跟目标变量的过去值没什么关系,还能用paddlets吗?比如y=2*x,y的未来值,是由协变量x决定的,跟y的过去值毫无关系,这时候,能用paddlets吗?
7.我没看过paddlets的模型代码,但我估计这个领域的模型都不大,换句话说,不太清楚paddleslim是否有用.但以我的经验,PaddleSlim用于paddlets,还是能降低使用者推理成本的,比如原来推理需要3090ti,就可以换成2070.拿图像分类来说,有些图像分类不难,只使用很小的神经网络就可以达到99准确率,用了paddleclas的最小模型进行分类的训练,然后用PaddleSlim剪枝量化等,生产出来的模型,相同机器下,推理速度大幅提升,或者是,推理速度不变,GPU,CPU成本大幅下降.总结,paddlets支持PaddleSlim还是很有用的,哈哈哈哈.

**Comment by Sunting78** [comment]
您好，您的建议收到。
