### ISSUE TITLE
AutoTS参数metric设置

### ISSUE THREAD

**Issue by Chase-brightstar** [PaddlePaddle/PaddleTS#264]
修改metric参数为mse，但实际训练评估使用的仍是mae。
metric (str) – metric的名字。metric 会被用于计算在 validation 数据集上的 loss，并反馈给超参优化算法。
<img width="989" alt="捕获" src="https://user-images.githubusercontent.com/82440069/203050644-9520bfd9-50f0-4ab8-b4ef-cee7af498288.PNG">

**Comment by LinWencong** [comment]
以你的代码为例子，这个参数的使用场景是， autots 在一个 trial（一组参数试验）结束之后，在 valid 数据集上计算 mse，并反馈给超参优化算法，是用于评估此trial 是好是坏的反馈数值；
