### ISSUE TITLE
关于TSDataset.load_from_dataframe方法参数的一些问题

### ISSUE THREAD

**Issue by bupt906** [PaddlePaddle/PaddleTS#266]
我是一个时序数据方面的新手，通过官方文档load自己的数据(数据时间间隔是不固定的)，输出的结果如下图所示。经过阅读源码发现是freq参数没有理解到位。我觉得pandas中的asfreq()方法其他参数也应该提供用户使用(例如：method和fill_value)这样可以让我这样的新手避免出现数据全是NAN的情况。
![d846c24d-42b4-439d-ba0d-24da37aacd2b](https://user-images.githubusercontent.com/41312357/203485634-766e782d-6b3b-472e-b928-f05c7708bc82.png)

**Comment by a10210532** [comment]
tsdataset的load方法提供了缺失值填充的选型，可以使用fill_missing_dates以及fillna_method参数进行配置；详情可以参考api文档 https://paddlets.readthedocs.io/zh_CN/latest/source/api/paddlets.datasets.tsdataset.html

**Comment by Hoogck** [comment]
如果不需要填充呢，因为有些场景本来就是缺数据的，像股票价格存在休盘和节假日的情况，怎么将缺失的两个时间点拼在一起？避免在训练过程中产生错误，比如：
1.ValueError: The `point` is out of the valid range
2.ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
。

**Comment by weibo021** [comment]
> 
TSDataset.load_from_dataframe
fillna_method='pre' #max, min, avg, median, pre, back, zero 
may 

Have you tried filling in the missing value data?
