### ISSUE TITLE
非常想学习PaddleTS，能不能开通下回放权限？

### ISSUE THREAD

**Issue by XSheng001** [PaddlePaddle/PaddleTS#267]
今天才报名PaddleTS课程学习，报名成功没法看课程回放，显示没有权限，特别想学习PaddleTS，能不能把回放的权限开启，或者怎有没有其他的途径去学习前面的课程？？

**Comment by zyn-sinde** [comment]
https://aistudio.baidu.com/aistudio/education/group/info/27798，可以尝试下这个链接

**Comment by XSheng001** [comment]
非常感谢！
