### ISSUE TITLE
AutoTS不支持Informer和DeepAR模型吗？

### ISSUE THREAD

**Issue by sly111** [PaddlePaddle/PaddleTS#275]
一使用`autots_informer=AutoTS(InformerModel, 24, 6)
autots_informer.fit(ts_train, ts_val)`
就提示`NotImplementedError: Unknown estimator`

**Comment by zyn-sinde** [comment]
暂时不支持，下一版本支持

**Comment by sly111** [comment]
> 

下个版本大概什么时候上线呀

**Comment by sly111** [comment]
> 

下个版本大概什么时候上线呀
