### ISSUE TITLE
 苹果macOS M1 arm64安装报错

### ISSUE THREAD

**Issue by wenzhaojie** [PaddlePaddle/PaddleTS#276]
PaddlePaddle官方已经支持 Mac M1芯片的运行。但是，PaddleTS却不能支持。
我看到PaddleTS中numpy依赖的版本是1.19.5，但是1.19.5并没有macOS的arm64的版本。

**Comment by QGN123** [comment]
报错信息辛苦贴下

**Comment by wenzhaojie** [comment]
本人macOS 13，MacBook Air M1芯片环境
创建环境步骤：
```shell
conda create -n paddle-ts python=3.8
conda activate -n paddle-ts

pip install paddlets
```
报错如下
```shell
(paddle-ts) wzj@Zhaojie-MBA ~ % pip install paddlets
Collecting statsmodels<=0.12.2,>=0.10.2
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/10/26/0fd61f95667e56fd597ecca715dff3623ed1122b6f895ed2b4dfb54afc04/statsmodels-0.12.2.tar.gz (17.5 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [3713 lines of output]
      Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
            
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by wenzhaojie** [comment]
> 本人macOS 13，MacBook Air M1芯片环境 创建环境步骤：
> 
> ```shell
> conda create -n paddle-ts python=3.8
> conda activate -n paddle-ts
> 
> pip install paddlets
> ```
> 
> 报错如下
> 
> ```shell
> (paddle-ts) wzj@Zhaojie-MBA ~ % pip install paddlets
> Collecting statsmodels<=0.12.2,>=0.10.2
>   Using cached https://pypi.tuna.tsinghua.edu.cn/packages/10/26/0fd61f95667e56fd597ecca715dff3623ed1122b6f895ed2b4dfb54afc04/statsmodels-0.12.2.tar.gz (17.5 MB)
>   Installing build dependencies ... error
>   error: subprocess-exited-with-error
>   
>   × pip subprocess to install build dependencies did not run successfully.
>   │ exit code: 1
>   ╰─> [3713 lines of output]
>       Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
>             
>       note: This is an issue with the package mentioned above, not pip.
>       hint: See above for output from the failure.
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × pip subprocess to install build dependencies did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> ```

@QGN123

**Comment by QGN123** [comment]
看上去不是numpy报错，换个安装源试试呢？

**Comment by QGN123** [comment]
目前这个版本的依赖我们是经过测试的，再M1上测试过是能够安装的， 辛苦您提供下python的具体版本，我们看看能不能复现问题~

**Comment by QGN123** [comment]
补充：python版本精确到小版本号& pip版本

**Comment by QGN123** [comment]
3.8.15是10月最新发布的版本，我们还未进行测试，这个问题我们会尽快去看。 建议您可以将python版本回退到3.8.13试下。

**Comment by QGN123** [comment]
![image](https://user-images.githubusercontent.com/38217558/206149692-0a1b4e3c-d66d-443d-8501-1ab12505563c.png)
测试了M1系统，python3.8.15,  pip 22.2.2 能够成功安装

**Comment by QGN123** [comment]
补充，测试系统为 M1 macos bigsur 11.4

**Comment by wenzhaojie** [comment]
> 补充，测试系统为 M1 macos bigsur 11.4

@QGN123 谢谢测试！我的环境是 macos 13.0.1，会报错。不过想请问您有配pip的镜像源吗？清华源和百度源都会有问题。

**Comment by QGN123** [comment]
①目前没有找到macos13的机器，后续会继续跟进这个问题， 目前看来有可能是macos13的兼容性问题。
②可以试下pypi源：pip install paddlets -i https://mirror.baidu.com/pypi/simple

**Comment by xonze** [comment]
mac m2 也不行，建议升级下，有几个依赖库都有支持问题，不光是numpy
