### ISSUE TITLE
AutoTS自动寻参的最佳模型如何保存？

### ISSUE THREAD

**Issue by yanglonghu** [PaddlePaddle/PaddleTS#277]
`AutoTS自动寻参完成的模型如何保存精度最高的模型，用.save()方法暂不支持，用 best_param 返回的最佳参数去加载一个新的模型训练完保存吗

**Comment by LinWencong** [comment]
同学你好，autots 的 fit 函数会返回最优模型~ 返回的模型是可以save()的哈；
autots实例比较复杂，我们暂时没有实现 save（）

**Comment by LinWencong** [comment]
best_model = autots_model.fit(train_dataset, val_dataset, n_trials=10)
best_model.save($your_path)
