### ISSUE TITLE
多路时序组成训练数据时 groupid 是否支持乱序输入？

### ISSUE THREAD

**Issue by JDanielWu** [PaddlePaddle/PaddleTS#281]
这个例子中，假如 id的顺序 是0，1交叉的，就报错了。不支持这种吗？

sample = pd.DataFrame(np.random.randn(200, 3), columns=['a', 'c', 'd'])
sample['id'] = pd.Series([0]*80 + [1]*120, name='id')

#Load TSDatasets by group_id
from paddlets import TSDataset
tsdatasets = TSDataset.load_from_dataframe(
    df=sample,
    group_id='id',
    target_cols='a',
    observed_cov_cols=['c', 'd'],
    #static_cov_cols='id'
)

**Comment by a10210532** [comment]
目前group_id 如果是乱序的话，目前需要指定time_col列，用于保障同一个group_id 的导入顺序
