### ISSUE TITLE
单元测试 test_MinMaxScaler 无法通过

### ISSUE THREAD

**Issue by 2Bear** [PaddlePaddle/PaddleTS#288]
```
paddlets\tests\transform\test_normalization.py
```

第50行：

```python
self.assertTrue(inverse1.get_known_cov().data.astype('int').equals(input1.get_known_cov().data))
```

`inverse1.get_known_cov().data.astype('int')` 与 `input1.get_known_cov().data` 永远不相等，

因为前者的dtype是`int32`，而后者是`int64`。如果修改成：

```python
self.assertTrue(inverse1.get_known_cov().data.astype('int').equals(input1.get_known_cov().data.astype('int')))
```

则可以顺利通过。

该单元测试中`test_MinMax`与`test_StandardScaler`这行代码出现了8次，都存在这个情况。

Python3.8 64bit

---

另外我发现该单元测试中`test_with_sklearn`也有类似的相等判断，但是两侧已经都加了`.astype('int')`，所以可以顺利通过。

**Comment by LinWencong** [comment]
@willionZS  关注；

**Comment by 2Bear** [comment]
merged.
