### ISSUE TITLE
TSDataset数据定义加载出错

### ISSUE THREAD

**Issue by tongbaiming** [PaddlePaddle/PaddleTS#304]
spyder 运行官网例子代码：
import numpy as np
import pandas as pd
from paddlets import TSDataset

x = np.linspace(-np.pi, np.pi, 200)
sinx = np.sin(x) * 4 + np.random.randn(200)
df = pd.DataFrame(
    {
        'time_col': pd.date_range('2022-01-01', periods=200, freq='1h'),
        'value': sinx,
        'known_cov_1': sinx + 4,
        'known_cov_2': sinx + 5,
        'observed_cov': sinx + 8,
        'static_cov': [1 for i in range(200)],
    }
)

target_dataset = TSDataset.load_from_dataframe(
    df,  #Also can be path to the CSV file
    time_col='time_col',
    target_cols='value',
    freq='1h'
)

输出：
[2022-12-16 18:45:10,564] [paddlets] [ERROR] ValueError: attr: shape doesn't exist!

**Comment by zyn-sinde** [comment]
请问用的pycharm ide什么版本呢，暂时没有复现你的这个问题

**Comment by tongbaiming** [comment]
我用的是spyder， 应该是spyder的variable explorer 不自持tsdataset,我把variable explorer的exclude unsupported data types 勾选就显示这个错误提示了
