### ISSUE TITLE
表征模型是否支持多变量

### ISSUE THREAD

**Issue by lim-0** [PaddlePaddle/PaddleTS#326]
请问一下表征模型是否支持多变量，在dataset中设置了known_cov_cols，然后使用CoST表征模型，但似乎没起作用，请问表征模型是否支持进行多变量训练，如果没有的话，如何才能在表征模型中使用多变量呢？

**Comment by Annnnnnnnnnnnn** [comment]
目前表征模型（CoST和TS2Vec）都是支持协变量的（包括observed和known）， 如果不符合预期，可以提供一下可复现代码的最小集合

**Comment by lim-0** [comment]
> 目前表征模型（CoST和TS2Vec）都是支持协变量的（包括observed和known）， 如果不符合预期，可以提供一下可复现代码的最小集合

好的，我自己再验证一下，谢谢
