### ISSUE TITLE
TCNRegressor回测存在偏移

### ISSUE THREAD

**Issue by lim-0** [PaddlePaddle/PaddleTS#329]
代码如下：
```python
ix_dataset2 = TSDataset.load_from_dataframe(
    data3,
    time_col='time',
    target_cols='ix',
    freq='1d',
    known_cov_cols=['work_day','holiday']
)

from paddlets.models.forecasting import MLPRegressor,LSTNetRegressor,TCNRegressor
md = TCNRegressor(
    in_chunk_len = 7,
    out_chunk_len = 1,
    max_epochs=100,
)

train_dataset, val_test_dataset = ix_dataset2.split(0.7)
val_dataset, test_dataset = val_test_dataset.split(0.5)
# train_dataset.plot(add_data=[val_dataset,test_dataset], labels=['Val', 'Test'])

md.fit(train_dataset, val_dataset)

from paddlets.utils import backtest
score, preds_data= backtest(
    data=test_dataset,
    model=md,
    return_predicts = True)
test_dataset.plot(add_data=preds_data,labels="backtest")
```
结果如下：
![image](https://user-images.githubusercontent.com/35923416/209530499-8d56813a-ec2f-4f56-92a9-2df9b5f2eadb.png)
预测趋势相当不错，但是存在明显偏移，请问这个是什么原因？求解答

**Comment by StevenL2017** [comment]
看起来是模型把上一期的真实值当做这一期的预测值了，预测1期滞后1期

**Comment by bianchuanxin** [comment]
1、模型在训练的时候没有学到足够的时序特征，如季节、趋势，而通过梯度下降发现预测值为最后一个时间步的特征值可以使得模型loss最小。
2、TCN模型不支持协变量，当sampling_stride为1时，模型学不到时间相关的信息，因此可以将sampling_stride设置为周期长度再尝试。
3、如果sampling_stride非要设为1，可以尝试其它的支持协变量的模型，并加入时间类可预知协变量，如RNN，Transformer, NBeats，Nhits，DeepAR等。

**Comment by Annnnnnnnnnnnn** [comment]
尝试从理论上分析：预测数据滞后于真实数据几乎是多步时间序列预测中必然会面临的挑战。
产生滞后问题的根本原因是：数据序列中产生了变化趋势，或者说是非线性非平稳序列，如果序列中随机变化的趋势频繁出现，且训练数据中找不到相应的规律，那么这个问题会更加放大。
用了某种算法做出来的测试集的平均绝对误差率都很好，但是把测试集的真实值及预测值画出来对比一下，就会发现t时刻的预测值往往是t-1时刻的真实值，也就是模型倾向于把上一时刻的真实值作为下一时刻的预测值，导致两条曲线存在滞后性，也就是真实值曲线滞后于预测值曲线。之所以会这样，是因为序列存在自相关性，如一阶自相关指的是当前时刻的值与其自身前一时刻值之间的相关性。因此，如果一个序列存在一阶自相关，模型学到的就是一阶相关性。而消除自相关性的办法就是进行差分运算。

**Comment by lim-0** [comment]
感谢解答！
