### ISSUE TITLE
请问应该怎么处理很多个比较短的序列的预测

### ISSUE THREAD

**Issue by xiehuanyi** [PaddlePaddle/PaddleTS#338]
我现在在处理的问题是有很多个比较短的序列，需要对每个序列分别预测他的未来的值，但是我阅读paddlets的文档后似乎没有找到相关的api，请问我可以通过什么方法来解决这样的问题呢？
我的数据可以看成是假设有1000只股票的数据，每只股票有过去30个星期的数据，我需要预测未来10个星期每个股票的走势，请问paddlets是否提供了相应的api？或者我可以通过什么方法来解决这一问题？

**Comment by QGN123** [comment]
可以看下多路数据联合训练的教程，可能会符合您的需求https://paddlets.readthedocs.io/zh_CN/latest/source/get_started/multiple_time_series.html

**Comment by weibo021** [comment]
> 可以看下多路数据联合训练的教程，可能会符合您的需求https://paddlets.readthedocs.io/zh_CN/latest/source/get_started/multiple_time_series.html

构造多时序数据组合tsdataset后，如何进行数据分割？直接调用splite报错，只能分别构造训练 验证和测试集吗？
