### ISSUE TITLE
anomaly_example中模型训练报ModuleNotFoundError: No module named 'more_itertools'错误

### ISSUE THREAD

**Issue by jiangxinufo** [PaddlePaddle/PaddleTS#344]
相关环境如下：
# Name                    Version                   Build  Channel
aiosignal                 1.2.0                    pypi_0    pypi
alembic                   1.8.1                    pypi_0    pypi
amqp                      5.1.1                    pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
asttokens                 2.1.0                    pypi_0    pypi
attrs                     22.1.0                   pypi_0    pypi
autopage                  0.5.1                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.11.1                   pypi_0    pypi
billiard                  3.6.4.0                  pypi_0    pypi
bleach                    5.0.1                    pypi_0    pypi
ca-certificates           2022.07.19           haa95532_0    https://mirrors.aliyun.com/anaconda/pkgs/main
celery                    5.2.7                    pypi_0    pypi
certifi                   2022.9.14        py38haa95532_0    https://mirrors.aliyun.com/anaconda/pkgs/main
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        2.1.1                    pypi_0    pypi
chinese-calendar          1.8.0                    pypi_0    pypi
click                     8.0.4                    pypi_0    pypi
click-didyoumean          0.3.0                    pypi_0    pypi
click-plugins             1.1.1                    pypi_0    pypi
click-repl                0.2.0                    pypi_0    pypi
cliff                     4.0.0                    pypi_0    pypi
cloudpickle               2.2.0                    pypi_0    pypi
cmaes                     0.8.2                    pypi_0    pypi
cmd2                      2.4.2                    pypi_0    pypi
colorama                  0.4.5                    pypi_0    pypi
colorlog                  6.7.0                    pypi_0    pypi
configspace               0.6.0                    pypi_0    pypi
contourpy                 1.0.5                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.32                  pypi_0    pypi
debugpy                   1.6.3                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
distlib                   0.3.6                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
fastjsonschema            2.16.2                   pypi_0    pypi
filelock                  3.8.0                    pypi_0    pypi
flaml                     1.0.12                   pypi_0    pypi
flask                     2.2.2                    pypi_0    pypi
flask-cors                3.0.10                   pypi_0    pypi
fonttools                 4.37.3                   pypi_0    pypi
frozenlist                1.3.1                    pypi_0    pypi
greenlet                  1.1.3                    pypi_0    pypi
grpcio                    1.43.0                   pypi_0    pypi
hpbandster                0.7.4                    pypi_0    pypi
idna                      3.4                      pypi_0    pypi
importlib-metadata        4.12.0                   pypi_0    pypi
importlib-resources       5.9.0                    pypi_0    pypi
ipykernel                 6.17.0                   pypi_0    pypi
ipython                   8.6.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.0.2                    pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
jsonschema                4.16.0                   pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            7.4.4                    pypi_0    pypi
jupyter-console           6.4.4                    pypi_0    pypi
jupyter-core              4.11.2                   pypi_0    pypi
jupyter-server            1.21.0                   pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-widgets        3.0.3                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
kombu                     5.2.4                    pypi_0    pypi
lightgbm                  3.3.2                    pypi_0    pypi
llvmlite                  0.39.1                   pypi_0    pypi
lxml                      4.9.1                    pypi_0    pypi
mako                      1.2.2                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.6.0                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
mistune                   2.0.4                    pypi_0    pypi
more-itertools            8.14.0                   pypi_0    pypi
mpmath                    1.2.1                    pypi_0    pypi
msgpack                   1.0.4                    pypi_0    pypi
nbclassic                 0.4.8                    pypi_0    pypi
nbclient                  0.7.0                    pypi_0    pypi
nbconvert                 7.2.3                    pypi_0    pypi
nbformat                  5.7.0                    pypi_0    pypi
nest-asyncio              1.5.6                    pypi_0    pypi
netifaces                 0.11.0                   pypi_0    pypi
notebook                  6.5.2                    pypi_0    pypi
notebook-shim             0.2.2                    pypi_0    pypi
numba                     0.56.4                   pypi_0    pypi
numpy                     1.19.5                   pypi_0    pypi
openssl                   1.1.1q               h2bbff1b_0    https://mirrors.aliyun.com/anaconda/pkgs/main
opt-einsum                3.3.0                    pypi_0    pypi
optuna                    3.0.3                    pypi_0    pypi
packaging                 21.3                     pypi_0    pypi
paddle-bfloat             0.1.7                    pypi_0    pypi
paddlepaddle-gpu          2.3.2                    pypi_0    pypi
paddlets                  1.1.0                    pypi_0    pypi
pandas                    1.3.5                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
patsy                     0.5.2                    pypi_0    pypi
pbr                       5.10.0                   pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.2.0                    pypi_0    pypi
pip                       22.1.2           py38haa95532_0    https://mirrors.aliyun.com/anaconda/pkgs/main
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              2.5.2                    pypi_0    pypi
prettytable               3.4.1                    pypi_0    pypi
prometheus-client         0.15.0                   pypi_0    pypi
prompt-toolkit            3.0.32                   pypi_0    pypi
protobuf                  3.20.0                   pypi_0    pypi
psutil                    5.9.3                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pygments                  2.13.0                   pypi_0    pypi
pyod                      1.0.6                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyperclip                 1.8.2                    pypi_0    pypi
pyreadline3               3.4.1                    pypi_0    pypi
pyro4                     4.82                     pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
python                    3.8.13               h6244533_0    https://mirrors.aliyun.com/anaconda/pkgs/main
python-dateutil           2.8.2                    pypi_0    pypi
python-docx               0.8.11                   pypi_0    pypi
pytz                      2022.2.1                 pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pywin32                   304                      pypi_0    pypi
pywinpty                  2.0.9                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     24.0.1                   pypi_0    pypi
qtconsole                 5.4.0                    pypi_0    pypi
qtpy                      2.2.1                    pypi_0    pypi
ray                       2.1.0                    pypi_0    pypi
requests                  2.28.1                   pypi_0    pypi
scikit-learn              1.1.2                    pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
seaborn                   0.12.1                   pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
serpent                   1.41                     pypi_0    pypi
setuptools                63.4.1           py38haa95532_0    https://mirrors.aliyun.com/anaconda/pkgs/main
shap                      0.41.0                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
slicer                    0.0.7                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
sqlalchemy                1.4.41                   pypi_0    pypi
sqlite                    3.39.2               h2bbff1b_0    https://mirrors.aliyun.com/anaconda/pkgs/main
stack-data                0.6.0                    pypi_0    pypi
statsmodels               0.12.2                   pypi_0    pypi
stevedore                 4.0.0                    pypi_0    pypi
sympy                     1.11.1                   pypi_0    pypi
tabulate                  0.8.10                   pypi_0    pypi
tensorboardx              2.5.1                    pypi_0    pypi
terminado                 0.17.0                   pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tornado                   6.2                      pypi_0    pypi
tqdm                      4.64.1                   pypi_0    pypi
traitlets                 5.5.0                    pypi_0    pypi
typing-extensions         4.3.0                    pypi_0    pypi
urllib3                   1.26.12                  pypi_0    pypi
vc                        14.2                 h21ff451_1    https://mirrors.aliyun.com/anaconda/pkgs/main
vine                      5.0.0                    pypi_0    pypi
virtualenv                20.16.5                  pypi_0    pypi
vs2015_runtime            14.27.29016          h5e58377_2    https://mirrors.aliyun.com/anaconda/pkgs/main
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.4.2                    pypi_0    pypi
werkzeug                  2.2.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0    https://mirrors.aliyun.com/anaconda/pkgs/main
widgetsnbextension        4.0.3                    pypi_0    pypi
wincertstore              0.2              py38haa95532_2    https://mirrors.aliyun.com/anaconda/pkgs/main
xgboost                   1.6.2                    pypi_0    pypi
zipp                      3.8.1                    pypi_0    pypi
# 报错部分代码：
import paddle
import numpy as np

# 固定随机随机种子，保证训练结果可复现
seed = 2022
paddle.seed(seed)
np.random.seed(seed)

#建模与训练
from paddlets.models.anomaly import AutoEncoder
model = AutoEncoder(
    in_chunk_len=2, # 样本数据窗口大小
    max_epochs=100  # 最大epoch设为100
)
model.fit(train_data_scaled)

#报错内容如下
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In [6], line 10
      7 np.random.seed(seed)
      9 #建模与训练
---> 10 from paddlets.models.anomaly import AutoEncoder
     11 model = AutoEncoder(
     12     in_chunk_len=2, # 样本数据窗口大小
     13     max_epochs=100  # 最大epoch设为100
     14 )
     15 model.fit(train_data_scaled)

File E:\Paddle-release-2.2\PaddleTS\paddlets\models\anomaly\__init__.py:8
      1 # !/usr/bin/env python3
      2 # -*- coding:utf-8 -*-
      4 """
      5 paddlets anomaly.
      6 """
----> 8 from paddlets.models.anomaly.dl.autoencoder import AutoEncoder
      9 from paddlets.models.anomaly.dl.anomaly_transformer import AnomalyTransformer
     10 from paddlets.models.anomaly.dl.vae import VAE

File E:\Paddle-release-2.2\PaddleTS\paddlets\models\anomaly\dl\autoencoder.py:15
     13 from paddlets.models.anomaly.dl._ed.ed import MLP, CNN
     14 from paddlets.models.common.callbacks import Callback
---> 15 from paddlets.models.anomaly.dl import utils as U
     16 from paddlets.datasets import TSDataset
     17 from paddlets.logger import raise_if, raise_if_not

File E:\Paddle-release-2.2\PaddleTS\paddlets\models\anomaly\dl\utils.py:11
      9 import paddle
     10 import paddle.nn.functional as F
---> 11 import more_itertools as mit
     13 from paddlets.logger import raise_if_not, raise_if, raise_log, Logger
     14 from paddlets.datasets import TSDataset

ModuleNotFoundError: No module named 'more_itertools'

**Comment by wangdong2222** [comment]
已沟通，应该是机器的环境没对齐，辛苦再检查下

**Comment by jiangxinufo** [comment]
感谢，问题已解决

**Comment by jiangxinufo** [comment]
感谢，问题已解决
