### ISSUE TITLE
Does TSDataset support slicing like dataframe? 

### ISSUE THREAD

**Issue by sysublackstar** [PaddlePaddle/PaddleTS#348]
Does TSDataset support slicing like dataframe? What I what to do is get a sub ts of a TSDataset object, the only way I found is to transform the TSDataset object to a DataFrame, then use .loc() to get a sub dataframe, and finally transform the dataframe to TSDataset again. It seems a liitle tedious.

**Comment by QGN123** [comment]
Sorry, TSDataset do not support slicing for now.  cuz target and know_covariants can be of deifferent length ,  it hard to define slice function in this situation.
