### ISSUE TITLE
Could not load library libcublasLt.so.10. Error

### ISSUE THREAD

**Issue by peterz3g** [PaddlePaddle/PaddleTS#357]
**已经安装好paddle库：**
paddle-bfloat==0.1.7
paddlepaddle-gpu==2.3.2.post110
paddlets==1.1.0

**nvidia-smi 查看显卡信息如下：**
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.191.01   Driver Version: 450.191.01   CUDA Version: 11.0     |

**根据网站提示验证安装是成功：**
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html#old-version-anchor-7-%E4%B8%89%E3%80%81%E9%AA%8C%E8%AF%81%E5%AE%89%E8%A3%85
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W0118 12:01:07.216766  1307 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.0, Runtime API Version: 11.0
W0118 12:01:07.218919  1307 gpu_resources.cc:91] device: 0, cuDNN Version: 8.7.
PaddlePaddle works well on 1 GPU.
PaddlePaddle works well on 1 GPUs.
**PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.**
>>> import paddlets
>>> paddlets.__version__
'1.1.0'

**执行DEMO报错：**
https://paddlets.readthedocs.io/zh_CN/latest/source/get_started/run_on_gpu.html
/usr/local/lib/python3.7/dist-packages/paddlets/utils/backtest.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import defaultdict, Iterable
W0117 17:57:11.007817   856 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.0, Runtime API Version: 11.0
W0117 17:57:11.010010   856 gpu_resources.cc:91] device: 0, cuDNN Version: 8.7.
/usr/local/lib/python3.7/dist-packages/paddle/nn/layer/norm.py:654: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
**Could not load library libcublasLt.so.10. Error: libcublasLt.so.10: cannot open shared object file: No such file or directory**

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
1   void paddle::imperative::Tracer::TraceOpImpl<paddle::imperative::VarBase>(std::string const&, paddle::imperative::details::NameVarMapTrait<paddle::imperative::VarBase>::Type const&, paddle::imperative::details::NameVarMapTrait<paddle::imperative::VarBase>::Type const&, paddle::framework::AttributeMap&, phi::Place const&, bool, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&, paddle::framework::AttributeMap*, bool)
2   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap const&, paddle::framework::AttributeMap const&)
3   phi::KernelImpl<void (*)(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&, float, float, std::string const&, bool, bool, bool, bool, phi::DenseTensor*, phi::DenseTensor*, phi::DenseTensor*, phi::DenseTensor*, phi::DenseTensor*, phi::DenseTensor*), &(void phi::BatchNormKernel<float, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&, float, float, std::string const&, bool, bool, bool, bool, phi::DenseTensor*, phi::DenseTensor*, phi::DenseTensor*, phi::DenseTensor*, phi::DenseTensor*, phi::DenseTensor*))>::Compute(phi::KernelContext*)
4   void phi::BatchNormKernel<float, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&, phi::DenseTensor const&, float, float, std::string const&, bool, bool, bool, bool, phi::DenseTensor*, phi::DenseTensor*, phi::DenseTensor*, phi::DenseTensor*, phi::DenseTensor*, phi::DenseTensor*)
5   phi::GPUContext::Impl::GetDnnHandle()
6   phi::InitDnnHandle(cudnnContext**, CUstream_st*, phi::Place)

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1673949432 (unix time) try "date -d @1673949432" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x358) received by PID 856 (TID 0x7f30f4919b80) from PID 856 ***]

Aborted (core dumped)

**Comment by Sunting78** [comment]
您好，可以确认下cuda安装，检查缺失的文件是否存在，以及可以配置指向CUDA库文件的路径。问题超过1个月自动关闭。
