### ISSUE TITLE
模型保存再训练问题

### ISSUE THREAD

**Issue by yutong12** [PaddlePaddle/PaddleTS#362]
您好
在使用时序预测模型对自有数据集fit后，如何在之前训练的基础上对新数据进行再训练？还是说每次都需要使用全部的数据重新训练

**Comment by a10210532** [comment]
目前paddlets通过save接口保存的模型，暂不支持导入后进行增量训练，只能直接用于推理；所以i目前通过全量数据的重训机制来解决模型更新的问题；如果有需求，可以说明一下使用场景，我们在下个版本升级支持一下

**Comment by yutong12** [comment]
我们计划将模型应用到异常流量检测上，通常情况下流量应该是稳定的；但如果某段时间有短期突发事件，例如连续一周加班，新员工入职，人资部举办线上活动等，会导致一段时间内的数据异常，在第一天应该能够检测到异常的流量，但在后续几天就应该将其聚合，其认定的异常应该是正常，因此希望有一个持续学习更新的能力。
