### ISSUE TITLE
Paddlets使用时，数据集日期是否必须是连续的日期，中间能否出现日期的中断

### ISSUE THREAD

**Issue by fadedol** [PaddlePaddle/PaddleTS#366]
![image](https://user-images.githubusercontent.com/87561504/217259824-334960e7-d66e-466d-b27a-26b4a3f5bd22.png)

![image](https://user-images.githubusercontent.com/87561504/217259946-a6809d5a-d156-44e2-8d1d-0a93c018286d.png)
![image](https://user-images.githubusercontent.com/87561504/217260088-2ea421a2-e22b-466a-8d21-62090905813a.png)
![image](https://user-images.githubusercontent.com/87561504/217261342-e225588b-2cb6-4dc4-bb9f-946d968371ea.png)
![image](https://user-images.githubusercontent.com/87561504/217261361-3f13fdd9-0f07-4c05-9d4f-8d9cff8c9c64.png)
![image](https://user-images.githubusercontent.com/87561504/217261375-f50d6c76-cf23-4674-9b8c-bfe4d4d9ae51.png)
在使用中我使用我自己的数据集，因为数据采样的问题，数据集中2018年和2020年某个时间段的数据无法使用（如第一张图所示，为我读取数据集的代码），导致数据集里的日期并不是完整的，除去无法利用的数据，共有34134条数据。当我完成数据可视化后，我想剔除的日期也被生成，但数据为空值，这些数据不能被利用于模型训练，并且划分好数据及后，数据集可视化也会显示出缺失数据的那段时间（如第二至四图，为数据可视化，其中原本不想被采用的日期也出现了，而不是直接从2017结束跳到2019）。最后使用模型训练时直接报错，错误是Input contains NaN（如图五图六）.我怀疑是缺失数据的那些日期也被划分进数据集中，导致这些日期中的各特征值为空值。如何避免这些问题，使得那些缺失数据的日期不被利用，还有划分数据集时这些缺失数据日期也不会被考虑。还是使用paddlets库时，必须是日期连续的数据集，不能出现日期的中断。

**Comment by weibo021** [comment]
time_col (str|None) – 时间列，可以是DatetimeIndex或者RangeIndex类型，如果为None，将index作为时间列
