### ISSUE TITLE
__init__() got an unexpected keyword argument 'pred_adjust'

### ISSUE THREAD

**Issue by aizaizai1989** [PaddlePaddle/PaddleTS#367]
from paddlets.models.anomaly import AutoEncoder

model = AutoEncoder(in_chunk_len=2, max_epochs=4,pred_adjust=True)
model.fit(No6_train_scaled)

在调用异常检测模块，想使用pred_adjust参数进行模型优化时，报错

**Comment by wangdong2222** [comment]
麻烦确认一下PaddleTS是否升级到最新版本(1.1.0)，如果不是，请升级到最新版本测试一下
