### ISSUE TITLE
时间序列间隔小于1S如何生成

### ISSUE THREAD

**Issue by qiyuezhiguang** [PaddlePaddle/PaddleTS#370]
在振动信号中，振动信号的采样频率非常高，1秒中有4096个点，这时如何生成序列time_col

#!coding=utf8

#导入其他库
import numpy as np
import pandas as pd
from scipy import loadmat
from matplotlib import pyplot as plt
from paddlets import TSDataset

#加载并解析mat文件
# loadmat函数能够载入mat数据，该数据是字典格式，以105为例，包括：['X105_DE_time','X105_FE_time','X105_BA_time','X102RPM']，分别为驱动端、风扇等数据
mat_data = loadmat("cwru_dataset/105.mat")['X105_DE_time'].squeeze()
# 生成时间序列，假设频率为4096Hz
shijian = np.linspace(0, (mat_data.size-1)/4096, mat_data.size)
# 转化为DataFrame格式
df = pd.DataFrame(
    {
        'time_col':shijian,
        'value': mat_data
    }
)
 #可以顺利实现
# 保存为csv格式文件

target_dataset = TSDataset.load_from_dataframe(
    df,  #Also can be path to the CSV file
    target_cols='value'
,time_col="time_col"
)
 #这里报错，time_col处错误，删除该部分即正常运行。但带来的结果是索引是1,2,3，……
因此，对于采样频率非常高的情况下，如何生成time_col

**Comment by wangdong2222** [comment]
这种情况一般没办法设置time_col了，可以用默认的1，2，3索引替代
