### ISSUE TITLE
known_cov使用方法的问题

### ISSUE THREAD

**Issue by Anyon123** [PaddlePaddle/PaddleTS#371]
仔细阅读了源码，产生了关于known_cov列使用方法的疑惑。文档中指出known_cov是指可在预测未来时间已知的变量，例如天气预报。

为什么在数据采样时用，known_cov列的长度取left和right两段长度（源码见paddlets.models.data_adapter.py 1286行至1310行），而在实际使用中其实只用到了和in_chunk_len一样长的数据（见paddlets.models.forecasting.dl.transformer.py 163行至182行）。

paddlets.models.data_adapter.py 1286行至1310行源码如下：
def _build_known_cov_for_single_sample(
        self,
        curr_sample_tail: int,
        timeindex_offset: int,
        known_cov_ndarray: np.ndarray
    ) -> np.ndarray:
        # known_cov can be combined with parts: left + right, while the skip_chunk will be SKIPPED.
        right_end = timeindex_offset + curr_sample_tail + 1
        right_start = (right_end - 1) - self._out_chunk_len + 1

        left_end = (right_end - 1) - self._out_chunk_len - self._skip_chunk_len + 1
        left_start = (left_end - 1) - self._in_chunk_len + 1
        return np.vstack(tup=(known_cov_ndarray[left_start:left_end], known_cov_ndarray[right_start:right_end]))

paddlets.models.forecasting.dl.transformer.py 163行至182行源码如下：
def _create_transformer_inputs(
        self, 
        X: Dict[str, paddle.Tensor]
    ) -> Tuple[paddle.Tensor, paddle.Tensor]:
        covs = [
            X[cov][:, :self._in_chunk_len, :] for cov in COVS if cov in X
        ]
        feats = [X[PAST_TARGET]] + covs
        src = paddle.concat(feats, axis=-1)
        tgt = src[:, -1:, :]
        return src, tgt

另外我看了好几个官方实现的算法示例，也都没有用到known_cov采样时的右段数据，不知道这个known_cov的意义在哪？

**Comment by a10210532** [comment]
这个是因为不同模型对于输入数据悠着不同的要求，有的模型能用到所谓的"右段数据 "，如tft；但是在设计上，是通用设计的~
