### ISSUE TITLE
请问PaddleTS如何设定实现让输出预测序列中每个点的间隔时间步数?

### ISSUE THREAD

**Issue by chunyisong** [PaddlePaddle/PaddleTS#380]
请问PaddleTS如何设定实现让输出预测序列中每个点的间隔时间步数?
比如,使用7*24小时的连续数据序列为输入,输出预测序列长度接下来24个小时内的为4时间点的预测值,也就是说该序列表示接下每隔6小时一个点共4个点(时间范围24小时)的输出结果.
input:[t1,t2,t3,...,t168],outpu:[t174,t180,t186,t192]

**Comment by Sunting78** [comment]
您好 可以设置skip=5实现您的需求。跳过中间的5小时，预测第六小时的数据。
