### ISSUE TITLE
我的数据集是每天7点到下午17点的统计数据,chunk可以怎么设置？

### ISSUE THREAD

**Issue by herbiel** [PaddlePaddle/PaddleTS#383]
in_chunk_len=7 * 24,
     out_chunk_len=24,

**Comment by Sunting78** [comment]
您好，in_chunk_len是您历史的长度，out_chunk_len是要预测的长度。如果是每一个小时一条数据，想用历史7天预测未来24小时的，那么in_chunk_len=7*24 ， out_chunk_len=24
