### ISSUE TITLE
时序数据的预测需不需要，在测试集中需不需要label或target。

### ISSUE THREAD

**Issue by marcocst** [PaddlePaddle/PaddleTS#384]
使用Informer模型，在训练集中是存在协变量和label，要求在测试集中进行预测，不过测试集中无label，只有协变量，请问可以进行时序预测吗

**Comment by Sunting78** [comment]
您好 时序预测的label您指的是target_col吗？测试集合只需要历史的target_col和协变量就可以预测未来的时序结果。问题超过1个月将关闭，谢谢理解。
