### ISSUE TITLE
啥时候加入“五边形战士”TimesNet？还有FEDformer和Autoformer等

### ISSUE THREAD

**Issue by lmqhello** [PaddlePaddle/PaddleTS#386]
啥时候扩充新模型呢

**Comment by Sunting78** [comment]
已经扩充，请试用

**Comment by lmqhello** [comment]
好的 非常点赞

**Comment by wghxiuyuan** [comment]
使用模型时
network = InceptionTimeClassifier(max_epochs=100, patience=10)
network.fit(ts_x_trains, y_train)
这里之后不能打印loss信息嘛？有没有什么途径可以观察训练过程

**Comment by Sunting78** [comment]
您好，这里是可以打印的，一个epoch打印一次，可能需要一个epoch训练完成才能观察到过程
