### ISSUE TITLE
SCINetModel和NLinearModel模型导入提示没有这个模块？

### ISSUE THREAD

**Issue by lmqhello** [PaddlePaddle/PaddleTS#387]
from paddlets.models.forecasting.dl import SCINetModel
from paddlets.models.forecasting.dl import NLinearModel

这两个执行的时候提示
ImportError: cannot import name 'SCINetModel' from 'paddlets.models.forecasting.dl' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlets/models/forecasting/dl/__init__.py)

进去看的话明明有这个文件啊

paddlepaddle版本2.4  paddlets版本1.1.0
请问是什么原因呢

**Comment by Sunting78** [comment]
您好 如果是通过pip install paddlets的方式安装，是没有的。这两个模型需要通过源码使用。
