### ISSUE TITLE
求助TS模型使用这里为什么会报错（仿造中国软件杯”大学生软件设计大赛——龙源风电赛道基线）

### ISSUE THREAD

**Issue by kuqiliya** [PaddlePaddle/PaddleTS#389]
![image](https://user-images.githubusercontent.com/130541990/231380992-db796490-8bfe-46c4-a7fc-f2ec9888adcb.png)
[000.csv](https://github.com/PaddlePaddle/PaddleTS/files/11208295/000.csv)
第一图为报错内容，第二文件为我的实验文件。

**Comment by Ni-Mr** [comment]
你为啥有这么多列输入

**Comment by Ni-Mr** [comment]
你把下面的spd_inst_max去掉就行，重复了

**Comment by kuqiliya** [comment]
> 你把下面的spd_inst_max去掉就行，重复了

可以请教一下这里面各项表达的是什么意思吗？小白不是很明白

**Comment by kuqiliya** [comment]
> 你把下面的spd_inst_max去掉就行，重复了

![image](https://user-images.githubusercontent.com/130541990/231442299-3032a84a-d781-469d-9386-e8fd4f370d83.png)
请问是这样更改吗？

**Comment by kuqiliya** [comment]
> 你把下面的spd_inst_max去掉就行，重复了

![image](https://user-images.githubusercontent.com/130541990/231442434-92a9f13e-460e-442e-953a-13fad17d4284.png)
请问是这样更改吗？下面有一串新的报错。

**Comment by Ni-Mr** [comment]
你逗号输成中文的了

**Comment by kuqiliya** [comment]
> 你逗号输成中文的了

![image](https://user-images.githubusercontent.com/130541990/231456180-2be12208-b866-4eaf-bbdc-48961ef0b21c.png)
这是更改过后，跟前面报了一样的错诶

**Comment by kuqiliya** [comment]
> 你逗号输成中文的了

大佬能再帮忙看一下吗？

**Comment by kuqiliya** [comment]
> known_cov与observed_cov不要有重复的
没有报错啦，谢谢大佬
