### ISSUE TITLE
PaddleTS案例模型

### ISSUE THREAD

**Issue by TheKingTao** [PaddlePaddle/PaddleTS#391]
最近PaddleTS能否多出一些案例典型教程呢？
最好能囊括较多常见的时序预测情况：
比如：
1. 在时序预测方面、表征学习方面、异常检测方面都能有几个典型案例，且案例的数据最好是能直接在PaddleTS的官方Github能下载到；
2. 在负荷预测和设备故障检测方面同上；
3. 案例最好能尽量多的囊括关键和基础的知识点，如果一个案例囊括不了想要表达的全部内容，那么可以在同一方面的多个案例之间有所互补表达；
4. 最后，预祝PaddleTS越做越好。

**Comment by Sunting78** [comment]
已经在scripts目录下 给出不同算法的案例 可一键训练
