### ISSUE TITLE
异常检测要求label必须是int，但无法将数据转换为int

### ISSUE THREAD

**Issue by ynzzmx** [PaddlePaddle/PaddleTS#397]
构建TSDataset后，int类型数据发生变化，变成了float
![图片](https://github.com/PaddlePaddle/PaddleTS/assets/128353785/7f1ef65f-1994-426b-811d-095175223457)
无法转换为int
![图片](https://github.com/PaddlePaddle/PaddleTS/assets/128353785/223cc956-945f-4804-964e-78c93234a52c)

**Comment by kachadx** [comment]
这个我也遇到，后面怎么解决的呢
