### ISSUE TITLE
PaddleTS中的TFT模型有大佬用过吗，或有没有这个模型的项目推荐

### ISSUE THREAD

**Issue by mendjks** [PaddlePaddle/PaddleTS#398]
为什么我用这个模型在生成预测曲线图时总是出现报错’ValueError: The specified columns don't exist!’

其他PaddleTS中的模型就不会

**Comment by mendjks** [comment]
紧急求助

**Comment by Sunting78** [comment]
您好，可以给出您具体的执行命令。我们尝试复现。另外根据报错，应该是您画图时的列名称在数据中不存在。
