### ISSUE TITLE
paddlets == 1.0.2 不支持一键动态转静态图

### ISSUE THREAD

**Issue by VocabVictor** [PaddlePaddle/PaddleTS#399]
我是直接使用官方文档（https://paddlets.readthedocs.io/zh_CN/latest/source/get_started/get_started.html）中的操作安装paddlets
```shell
pip install paddlets[all]
``` 
pip使用阿里镜像，应该不存在和PYPI版本错位的问题。但是当我准备按照官方文档所说的，使用save方法一键将动态图转静态图时，发生错误如下：
```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[161], line 1
----> 1 lstm.save("./lstm", network_model=True, dygraph_to_static=True)

TypeError: save() got an unexpected keyword argument 'network_model'
``` 
我将github源码拷贝下来，全局查看，两个参数都是存在的。但是我所安装的paddlets中没有，请问是否存在上传到PYPI中的安装文件和github版本存在错位？

**Comment by Sunting78** [comment]
您好，使用pip安装的版本是旧版本，没有支持静态图保存。如果想使用该功能可以用源码。
