### ISSUE TITLE
拆分运行完成后出现如下所示的错误

### ISSUE THREAD

**Issue by yuxiaotongshenzhen** [PaddlePaddle/PaddleTS#405]
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::platform::MKLDNNDeviceContextThreadLocals::Body::~Body()
1   paddle::platform::MKLDNNDeviceContext::ResetBlobMap(void*)

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1685674949 (unix time) try "date -d @1685674949" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x15cb9) received by PID 89273 (TID 0x7f17c8938740) from PID 89273 ***]

Aborted

问题背景：
使用分组联合训练进行训练，将所有代码放到一个py文件执行时未出现该错误；成功执行完毕；
将上述py文件拆分成predict.py；analysizes.py，main.py和conf.py后出现这个bug;程序执行完成的时候出现这个问题

**Comment by Sunting78** [comment]
您好，麻烦给出具体命令和完整的报错信息，考虑可能是cuda/cudnn版本问题。
