### ISSUE TITLE
安装运行示例代码报warrning

### ISSUE THREAD

**Issue by freedomaswind94** [PaddlePaddle/PaddleTS#410]

**Comment by freedomaswind94** [comment]
D:\ProgramData\Anaconda3\envs\paddleTS\lib\site-packages\pkg_resources\__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
D:\ProgramData\Anaconda3\envs\paddleTS\lib\site-packages\pkg_resources\__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
D:\ProgramData\Anaconda3\envs\paddleTS\lib\site-packages\pkg_resources\__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
D:\ProgramData\Anaconda3\envs\paddleTS\lib\site-packages\paddlets\utils\backtest.py:6: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import defaultdict, Iterable
D:\ProgramData\Anaconda3\envs\paddleTS\lib\site-packages\statsmodels\compat\pandas.py:12: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  version = LooseVersion(pd.__version__)
D:\ProgramData\Anaconda3\envs\paddleTS\lib\site-packages\statsmodels\compat\pandas.py:14: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  pandas_lt_1_0_0 = version < LooseVersion('1.0.0')
D:\ProgramData\Anaconda3\envs\paddleTS\lib\site-packages\statsmodels\compat\pandas.py:15: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  pandas_lt_25_0 = version < LooseVersion('0.25.0')
D:\ProgramData\Anaconda3\envs\paddleTS\lib\site-packages\statsmodels\compat\pandas.py:16: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  pandas_gte_23_0 = version >= LooseVersion('0.23.0')
D:\ProgramData\Anaconda3\envs\paddleTS\lib\site-packages\statsmodels\compat\scipy.py:6: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SP_VERSION = LooseVersion(scipy.__version__)
D:\ProgramData\Anaconda3\envs\paddleTS\lib\site-packages\statsmodels\compat\scipy.py:7: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SCIPY_11 = SP_VERSION < LooseVersion("1.2.0")
D:\ProgramData\Anaconda3\envs\paddleTS\lib\site-packages\statsmodels\compat\scipy.py:10: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SCIPY_GT_14 = SP_VERSION >= LooseVersion("1.5")
D:\ProgramData\Anaconda3\envs\paddleTS\lib\site-packages\statsmodels\compat\scipy.py:11: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SP_LT_15 = SP_VERSION < LooseVersion("1.5")
D:\ProgramData\Anaconda3\envs\paddleTS\lib\site-packages\statsmodels\compat\numpy.py:46: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  NP_LT_114 = LooseVersion(np.__version__) < LooseVersion('1.14')

Process finished with exit code 0

**Comment by freedomaswind94** [comment]
import pandas as pd
import numpy as np
from paddlets import TSDataset

x = np.linspace(-np.pi, np.pi, 200)
sinx = np.sin(x) * 4 + np.random.randn(200)

df = pd.DataFrame(
    {
        'time_col': pd.date_range('2022-01-01', periods=200, freq='1h'),
        'value': sinx
    }
)
custom_dataset = TSDataset.load_from_dataframe(
    df,  #Also can be path to the CSV file
    time_col='time_col',
    target_cols='value',
    freq='1h'
)

**Comment by freedomaswind94** [comment]
运行上面的代码，为啥会报警告，怎么样不警告

**Comment by freedomaswind94** [comment]
而且import paddlets 也会直接报警告

**Comment by Sunting78** [comment]
尝试忽略
import warnings
warnings.filterwarnings("ignore")

**Comment by Sunting78** [comment]
超过一个月用户未回复的问题将自动关闭。
