### ISSUE TITLE
依赖更新建议

### ISSUE THREAD

**Issue by Miracle0x0** [PaddlePaddle/PaddleTS#411]
目前使用的 paddlets==1.1.0，paddlepaddle-gpu==2.4.2.post117，python 版本 3.8，能够友好共存的最高版本 numpy==1.19.5，pandas==1.3.5，而一些 package 例如 Prophet 的最低依赖要求 numpy > 1.21，希望能够更新一下依赖问题。

**Comment by Sunting78** [comment]
您好 会维护更新
