### ISSUE TITLE
表征模型报错

### ISSUE THREAD

**Issue by Erling-J** [PaddlePaddle/PaddleTS#417]
在运行ts2vec和CoST模型时，fit函数正常运行，但在进行encode时报错

AttributeError: '_DataLoaderIterSingleProcess' object has no attribute 'next'

**Comment by WKangei** [comment]
试试paddlepaddle==2.3.1

**Comment by Sunting78** [comment]
您好 请提供具体的环境和运行命令

**Comment by Sunting78** [comment]
您好，问题超过1周将关闭。感谢理解。
