### ISSUE TITLE
Crossformer模型训练失败

### ISSUE THREAD

**Issue by akari0216** [PaddlePaddle/PaddleTS#422]
`
import paddlets
from paddlets.datasets.repository import get_dataset, dataset_list
from paddlets.datasets import TSDataset

dataset = get_dataset('UNI_WTH')
train_dataset, val_test_dataset = dataset.split(0.7)
val_dataset, test_dataset = val_test_dataset.split(0.5)
train_dataset.plot(add_data=[val_dataset,test_dataset], labels=['Val', 'Test'])

from paddlets.models.forecasting import Crossformer

cf = Crossformer(
    c_in = 5, 
    factor = 10, 
    in_chunk_len = 24,
    out_chunk_len = 24,
    max_epochs=10, 
)
cf.fit(train_dataset, val_dataset)
`

运行以上代码后报错：
`
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_266/260518010.py in <module>
      8     max_epochs=10,
      9 )
---> 10 cf.fit(train_dataset, val_dataset)

~/paddlets/models/forecasting/dl/paddle_base_impl.py in fit(self, train_tsdataset, valid_tsdataset)
    347         train_dataloader, valid_dataloaders = self._init_fit_dataloaders(
    348             train_tsdataset, valid_tsdataset)
--> 349         self._fit(train_dataloader, valid_dataloaders)
    350 
    351     def _fit(self,

~/paddlets/models/forecasting/dl/paddle_base_impl.py in _fit(self, train_dataloader, valid_dataloaders)
    371             # Call the `on_epoch_begin` method of each callback before the epoch starts.
    372             self._callback_container.on_epoch_begin(epoch_idx)
--> 373             self._train_epoch(train_dataloader)
    374             # Predict for each eval set.
    375             for eval_name, valid_dataloader in zip(valid_names,

~/paddlets/models/forecasting/dl/paddle_base_impl.py in _train_epoch(self, train_loader)
    433             self._callback_container.on_batch_begin(batch_idx)
    434             X, y = self._prepare_X_y(data)
--> 435             batch_logs = self._train_batch(X, y)
    436             self._callback_container.on_batch_end(batch_idx, batch_logs)
    437         epoch_logs = {"lr": self._optimizer.get_lr()}

~/paddlets/models/forecasting/dl/paddle_base_impl.py in _train_batch(self, X, y)
    449             Dict[str, Any]: Dict of logs.
    450         """
--> 451         output = self._network(X)
    452         loss = self._compute_loss(output, y)
    453         loss.backward()

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in __call__(self, *inputs, **kwargs)
    946             and (not self._forward_post_hooks) and (not self._built) and in_dygraph_mode() and (not in_profiler_mode()):
    947             self._build_once(*inputs, **kwargs)
--> 948             return self.forward(*inputs, **kwargs)
    949         else:
    950             return self._dygraph_call_func(*inputs, **kwargs)

~/paddlets/models/forecasting/dl/Crossformer.py in forward(self, x)
     85         x_seq += self.enc_pos_embedding
     86         x_seq = self.pre_norm(x_seq)
---> 87         enc_out = self.encoder(x_seq)
     88         dec_in = repeat(self.dec_pos_embedding,
     89             'b ts_d l d -> (repeat b) ts_d l d', repeat=batch_size)

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in __call__(self, *inputs, **kwargs)
    946             and (not self._forward_post_hooks) and (not self._built) and in_dygraph_mode() and (not in_profiler_mode()):
    947             self._build_once(*inputs, **kwargs)
--> 948             return self.forward(*inputs, **kwargs)
    949         else:
    950             return self._dygraph_call_func(*inputs, **kwargs)

~/paddlets/models/forecasting/dl/_crossformer/encoder.py in forward(self, x)
     87         encode_x.append(x)
     88         for block in self.encode_blocks:
---> 89             x = block(x)
     90             encode_x.append(x)
     91         return encode_x

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in __call__(self, *inputs, **kwargs)
    946             and (not self._forward_post_hooks) and (not self._built) and in_dygraph_mode() and (not in_profiler_mode()):
    947             self._build_once(*inputs, **kwargs)
--> 948             return self.forward(*inputs, **kwargs)
    949         else:
    950             return self._dygraph_call_func(*inputs, **kwargs)

~/paddlets/models/forecasting/dl/_crossformer/encoder.py in forward(self, x)
     61         _, ts_dim, _, _ = x.shape
     62         if self.merge_layer is not None:
---> 63             x = self.merge_layer(x)
     64         for layer in self.encode_layers:
     65             x = layer(x)

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in __call__(self, *inputs, **kwargs)
    946             and (not self._forward_post_hooks) and (not self._built) and in_dygraph_mode() and (not in_profiler_mode()):
    947             self._build_once(*inputs, **kwargs)
--> 948             return self.forward(*inputs, **kwargs)
    949         else:
    950             return self._dygraph_call_func(*inputs, **kwargs)

~/paddlets/models/forecasting/dl/_crossformer/encoder.py in forward(self, x)
     31         seg_to_merge = []
     32         for i in range(self.win_size):
---> 33             seg_to_merge.append(x[:, :, i::self.win_size, :])
     34         x = paddle.concat(x=seg_to_merge, axis=-1)
     35         x = self.norm(x)

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py in __getitem__(self, item)
    751         else:
    752             # 2. Call c++ func getitem_index_not_tensor to speedup.
--> 753             return self._getitem_index_not_tensor(item)
    754 
    755     def __setitem__(self, item, value):

ValueError: (InvalidArgument) The start index and end index are invalid for their corresponding stride.
  [Hint: Expected neg_dim_condition == false, but received neg_dim_condition:1 != false:0.] (at /paddle/paddle/phi/kernels/funcs/strided_slice.h:100)
`

环境：
Aistudio, python == 3.7.4, paddlepaddle-gpu == 2.4.0.post112

**Comment by Sunting78** [comment]
其他数据集可以尝试下，看是否有一样的问题？
我们也排查下 谢谢使用
