### ISSUE TITLE
项目组什么时候发布新版本更新？

### ISSUE THREAD

**Issue by cgd139** [PaddlePaddle/PaddleTS#424]
paddlets易用性很好，不过相比其它同类库功能还不够强大，请问项目组什么时候发布新版本更新？

**Comment by Sunting78** [comment]
可以给出功能建议，我们会逐步加入。
目前已经更新了最新的深度算法，可以尝试使用

**Comment by Sunting78** [comment]
您好，暂时没有发布计划，可以通过源码使用，或者推荐可以使用PaddleX时序预测模型。欢迎尝试使用PaddleX 2.2 进行训练，https://aistudio.baidu.com/intro/paddlex
