### ISSUE TITLE
运行informer时碰到TSDataset.target.time_index[time_window[1]]越界报错

### ISSUE THREAD

**Issue by voyagebio** [PaddlePaddle/PaddleTS#429]
具体报错是这样，在运行.predict(test_dataset)函数时，碰到这样的问题
[paddlets] [ERROR] ValueError: The inequality must hold: TSDataset.known_cov.start_time (2013-02-01 00:00:00) <= TSDataset.target.time_index[(time_window[0] - out_chunk_len - skip_chunk_len - in_chunk_len + 1)] (2013-02-28 21:00:00) <= TSDataset.target.time_index[time_window[1]] (2013-03-01 00:00:00) <= TSDataset.known_cov.end_time (2013-02-28 23:00:00).

然后我就去查time_window是啥玩意，在paddle_base_impl.py文件中，定义是这样的：
boundary = (len(tsdataset.get_target().data) - 1 + self._skip_chunk_len
                    + self._out_chunk_len)
time_window=(boundary, boundary)

那么有疑问的就来了，boundary肯定会大于len(tsdataset.get_target().data)，也就是比tsdataset长度要长，那么TSDataset.target.time_index[time_window[1]]必定会越界啊

求大佬捞捞。
---------------------------------------------------------------------------------------------------------------------------------
具体代码：from paddlets.models.forecasting import InformerModel
InF = InformerModel(
    in_chunk_len=3,
    out_chunk_len=1,
    max_epochs=2)
InF.fit(train_dataset, val_dataset)
subset_test_pred_dataset = InF.predict(test_dataset)#模型预测
subset_test_dataset, _ = test_dataset.split(len(subset_test_pred_dataset.target))#截取某天进行预测
subset_test_dataset.plot(add_data=subset_test_pred_dataset, labels=['Pred'])
from paddlets.utils import backtest
score, preds_data= backtest(
    data=test_dataset,
    model=InF,
    return_predicts = True)
print(f"mae: {score}")
test_dataset.plot(add_data=preds_data,labels="backtest")
---------------------------------------------------------------------------------------------------------------------------------------
具体报错：---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_181/2058596484.py in <module>
      5     max_epochs=3)
      6 InF.fit(train_dataset, val_dataset)
----> 7 subset_test_pred_dataset = InF.predict(test_dataset)#模型预测
      8 subset_test_dataset, _ = test_dataset.split(len(subset_test_pred_dataset.target))#截取某天进行预测
      9 subset_test_dataset.plot(add_data=subset_test_pred_dataset, labels=['Pred'])

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlets/models/utils.py in wrapper(obj, tsdataset, **kwargs)
    113             )
    114 
--> 115             results = func(obj, tsdataset, **kwargs)
    116             if scenario == "anomaly_label" or scenario == "anomaly_score":
    117                 # Generate target cols

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlets/models/forecasting/dl/paddle_base_impl.py in predict(self, tsdataset)
    400             TSDataset.
    401         """
--> 402         dataloader = self._init_predict_dataloader(tsdataset)
    403         return self._predict(dataloader)
    404 

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlets/models/forecasting/dl/paddle_base_impl.py in _init_predict_dataloader(self, tsdataset)
    261             skip_chunk_len=self._skip_chunk_len,
    262             sampling_stride=self._sampling_stride,
--> 263             time_window=(boundary, boundary)
    264         )
    265         dataloader = data_adapter.to_paddle_dataloader(dataset, self._batch_size)

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlets/models/data_adapter.py in to_sample_dataset(self, rawdataset, in_chunk_len, out_chunk_len, skip_chunk_len, sampling_stride, fill_last_value, time_window)
   1512             sampling_stride=sampling_stride,
   1513             time_window=time_window,
-> 1514             fill_last_value=fill_last_value
   1515         )
   1516 

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlets/models/data_adapter.py in __init__(self, rawdataset, in_chunk_len, out_chunk_len, skip_chunk_len, sampling_stride, fill_last_value, time_window)
    341         # perform the rest of the timeseries validation.
    342         self._validate_target_timeseries()
--> 343         self._validate_known_cov_timeseries()
    344         self._validate_observed_cov_timeseries()
    345 

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlets/models/data_adapter.py in _validate_known_cov_timeseries(self)
   1005                 f"TSDataset.{self._std_timeseries_name}.time_index[time_window[1]] " +
   1006                 f"({sample_end_std_time}) <= " +
-> 1007                 f"TSDataset.known_cov.end_time ({known_cov_ts.end_time})."
   1008             )
   1009 

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlets/logger/logger.py in raise_if_not(condition, message, logger)
    133     if not condition:
    134         logger.error("ValueError: " + message)
--> 135         raise ValueError(message)
    136 
    137 

ValueError: The inequality must hold: TSDataset.known_cov.start_time (2013-02-01 00:00:00) <= TSDataset.target.time_index[(time_window[0] - out_chunk_len - skip_chunk_len - in_chunk_len + 1)] (2013-02-28 21:00:00) <= TSDataset.target.time_index[time_window[1]] (2013-03-01 00:00:00) <= TSDataset.known_cov.end_time (2013-02-28 23:00:00).

**Comment by 1878708493** [comment]
解决了吗？我也碰到同样的问题，不知道是不是系统的bug

**Comment by Sunting78** [comment]
因为你加入了时间特征，时间特征是已知的协变量，需要给预测的时间点也加入时间特征。可以参考以下代码进行修改，加入extend_points补全时间特征
            time_feature_generator = TimeFeatureGenerator(
                feature_cols=[
                    'hourofday', 'dayofmonth', 'dayofweek', 'dayofyear'
                ],
                extend_points=model._out_chunk_len + 1)
            ts_test = time_feature_generator.fit_transform(ts_test)
