### ISSUE TITLE
plot()方法无法显示图片，命令行报错shape doesn't exist!

### ISSUE THREAD

**Issue by IAmMsx** [PaddlePaddle/PaddleTS#443]
环境是我新建的一个conda环境，运行了如下命令：
conda create -n pts python=3.8 # 创建环境
python -m pip install paddlepaddle==2.5.1 -i https://mirror.baidu.com/pypi/simple # 部署paddle
pip install paddlets -i https://mirror.baidu.com/pypi/simple # 部署paddlets

程序是paddlets官方文档中2.2 构建自定义数据集的例子
![image](https://github.com/PaddlePaddle/PaddleTS/assets/33619303/439f9204-2f1f-4e87-8309-99cc98d02827)

**Comment by IAmMsx** [comment]
还是上方的环境，官方文档里概率预测的例子，换了个rnn模型，到model.fit会直接退出进程
在控制台单步运行，上方数据处理部分会报valueError的错误，但是能得到处理结果
![image](https://github.com/PaddlePaddle/PaddleTS/assets/33619303/5e408a21-71bb-4744-ba67-def58c6c2984)

**Comment by Sunting78** [comment]
您好，我们复现跟进下

**Comment by dsqzhou** [comment]
您好，第一个问题我在相同环境复现了，没有报错，可以debug看下是在哪一步报错的

**Comment by Sunting78** [comment]
您好，由于问题超过一周，将自动关闭。
