### ISSUE TITLE
表征模型中对标签列数据处理bug

### ISSUE THREAD

**Issue by lz-xinlin** [PaddlePaddle/PaddleTS#444]
你好,我在使用中发现表征模型中对标签列数据直接使用了当前时间的值,我认为这存在严重的数据泄露问题

**Comment by lz-xinlin** [comment]
@Sunting78

**Comment by lz-xinlin** [comment]
是没人处理还是说你们觉得这个不是bug

**Comment by Sunting78** [comment]
您好，抱歉，我们暂未发现您所提到的问题，请您提供下运行代码，我们跟进复现下。

**Comment by Sunting78** [comment]
长时间未回复，该issue已关闭，如仍有问题可以reopen或新开issue。
