### ISSUE TITLE
ensemble模型保存成文件后再加载预测报错

### ISSUE THREAD

**Issue by kingwpf** [PaddlePaddle/PaddleTS#446]
保存方式:
<img width="751" alt="image" src="https://github.com/PaddlePaddle/PaddleTS/assets/10610290/cde6d45f-ac10-4dce-8438-406dacf0a2a3">

加载方式:
<img width="662" alt="image" src="https://github.com/PaddlePaddle/PaddleTS/assets/10610290/04aee46d-a9d3-46e0-9a53-51b6b38e54bd">

line 125, in _predict_estimators
    for estimator in self._estimators:
TypeError: 'int' object is not iterable

**Comment by kingwpf** [comment]
如果按训练代码重新创建StackingEnsembleForecaster对象，然后用.load加载训练好的模型，还是有报错：

首先是backtest预测前会判断模型self._fitted是否为True，接着我手动把self._fitted设置为True后。paddlets/models/forecasting/dl/paddle_base_impl.py里面的self._network.eval()处又报AttributeError: 'NoneType' object has no attribute 'eval'

**Comment by kingwpf** [comment]
后面试了一下直接把训练好的stacking模型直接用pickle.dump下来，但是提示对象无法dump

**Comment by BowenFF** [comment]
我也遇到了这个问题，请问有什么解决方案吗

**Comment by kingwpf** [comment]
> 我也遇到了这个问题，请问有什么解决方案吗

换框架，这个项目他们基本不维护了，跑出来的结果也怪怪的。
https://github.com/unit8co/darts
