### ISSUE TITLE
项目代码拉下来就有冲突

### ISSUE THREAD

**Issue by kingwpf** [PaddlePaddle/PaddleTS#447]
nlinear.py和NLinear.py
<img width="629" alt="image" src="https://github.com/PaddlePaddle/PaddleTS/assets/10610290/70e8e77a-1e76-418d-a1a1-8287886bf05e">

**Comment by Sunting78** [comment]
名字可能有重复。后面会修改

**Comment by Sunting78** [comment]
已经修复
