### ISSUE TITLE
timeseries有个小问题

### ISSUE THREAD

**Issue by Kaiakaiakai** [PaddlePaddle/PaddleTS#449]
在timeseries的load_from_dataframe方法里面
        #Try to convert to string and generate DatetimeIndex
        if np.issubdtype(time_col_vals.dtype, np.integer) and isinstance(freq, str):
            time_col_vals = time_col_vals.astype(str)
这里跟之后的代码好像冲突了

**Comment by Sunting78** [comment]
您好，可以此处粘贴下报错吗？
