### ISSUE TITLE
模型协变量已知列对预测没有影响。

### ISSUE THREAD

**Issue by Chouett** [PaddlePaddle/PaddleTS#450]
<b>用MLP/LSTNet等模型进行paddlets训练时添加了已知列（known_cols），但在调用模型预测时，发现已知列的数据对预测结果没有任何影响，甚至待预测数据中没有已知列也不会报错。</b>

`

tsDataset = TSDataset.load_from_dataframe(
    df,
    time_col='monitorTime', target_cols='power', freq='5min',
    # known_cov_cols=['fushe'],
    fill_missing_dates=True,
    fillna_method='pre'
)
mod = LSTNetRegressor.load("work/lstm_lxh/LSTNetRegressor")
predict_result = mod.predict(predicted_data)

`

<b>known_cov_cols=['fushe'], 该行注释与否对运行和预测结果毫无影响</b>

而相同的错误情况，在pipeline训练和预测中就不存在。

**Comment by Chouett** [comment]
# 训练时，设定known_cov_cols=['fushe']
# 预测时注释掉该行仍然正常预测，取消注释也对预测结果没有影响。
tsDataset = TSDataset.load_from_dataframe(
    df,
    time_col='monitorTime', target_cols='power', freq='5min',
    # known_cov_cols=['fushe'],
    fill_missing_dates=True,
    fillna_method='pre'
)
mod = LSTNetRegressor.load("work/lstm_lxh/LSTNetRegressor")
predict_result = mod.predict(predicted_data)
# 无论known_cov_cols=['fushe']注释与否，predict_result 结果始终一样。
print(predict_result)

**Comment by Sunting78** [comment]
您好，MLP/LSTNet 是不支持协变量的

**Comment by YuboCoco** [comment]
> 您好，MLP/LSTNet 是不支持协变量的

请问那LSTNet如何进行MS任务呢？只能单纯的做针对Target的时间序列预测吗？可否引入其他Features？

**Comment by YuboCoco** [comment]
> 是的，如果希望引入其他协助变量，可以使用RNN / NBeats / Non-stationary transformer等模型。

请问PaddleTS中是否有集成Non-stationary transformer呢？

**Comment by Sunting78** [comment]
有的。https://github.com/PaddlePaddle/PaddleTS/blob/main/configs/longterm_forecast/Nonstationary_ECL.yaml
