### ISSUE TITLE
训练无报错，自动关闭程序

### ISSUE THREAD

**Issue by xiaoyao123456789** [PaddlePaddle/PaddleTS#460]
import socket
import pandas as pd
import json
from paddlets import TSDataset
from paddlets.models.forecasting import MLPRegressor
import paddlets
print(paddlets.__version__)

mlp = MLPRegressor(in_chunk_len=30, out_chunk_len=1, max_epochs=100)
data = pd.read_excel(r"D:\Yy\Downloads\Newflow.xls")
data['flow'] = data['flow'].astype('float64')
custom_dataset = TSDataset.load_from_dataframe(data, time_col='time_flag', target_cols='flow', freq='1min')
mlp.fit(custom_dataset)
subset_test_pred_dataset = mlp.recursive_predict(custom_dataset, 30)

print("subset_test_pred_dataset     ↓↓↓  \n      ")
print(subset_test_pred_dataset)
# Get the predictions as a JSON-formatted string
print("--------------------------------------------------------------------")
subset_test_pred_dataset.target.data.reset_index(inplace=True)
subset_test_pred_dataset.target.data.columns = ["time_flag", "flow"]

print(subset_test_pred_dataset.target.data)

formatted_predictions = str({"predict": [{"time_flag": str(entry["time_flag"]), "flow": int(entry["flow"])} for _, entry in subset_test_pred_dataset.target.data.iterrows()]}) + "\r\n"
print(formatted_predictions)

没有报错，打印了数据信息后  到了fit以后就打印了如下信息就自动关闭程序了
[2023-11-03 14:36:58,262] [paddlets.models.forecasting.dl.paddle_base_impl] [WARNING] No early stopping will be performed, last training weights will be used.
W1103 14:36:58.309204 25456 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.7
W1103 14:36:58.371068 25456 gpu_resources.cc:149] device: 0, cuDNN Version: 8.4.

**Comment by JackieLieu** [comment]
遇到同样问题，请问解决了没

**Comment by JackieLieu** [comment]
把 paddle 的版本由2.5 改成2.4.2 就可以了
