### ISSUE TITLE
[paddlets.__call__():89] [ERROR] ValueError: attr: shape doesn't exist!

### ISSUE THREAD

**Issue by JackieLieu** [PaddlePaddle/PaddleTS#461]
paddlepaddle 版本 2.4.2   paddlets 版本1.1.0  python 版本 3.8

运行官网demo时总是报以下警告：
1、  [paddlets.__call__():89] [ERROR] ValueError: attr: shape doesn't exist!
2、

C:\Users\wyd_h\.conda\envs\python3.8\lib\site-packages\statsmodels\compat\pandas.py:12: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  version = LooseVersion(pd.__version__)
C:\Users\wyd_h\.conda\envs\python3.8\lib\site-packages\statsmodels\compat\pandas.py:14: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  pandas_lt_1_0_0 = version < LooseVersion('1.0.0')
C:\Users\wyd_h\.conda\envs\python3.8\lib\site-packages\statsmodels\compat\pandas.py:15: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  pandas_lt_25_0 = version < LooseVersion('0.25.0')
C:\Users\wyd_h\.conda\envs\python3.8\lib\site-packages\statsmodels\compat\pandas.py:16: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  pandas_gte_23_0 = version >= LooseVersion('0.23.0')
C:\Users\wyd_h\.conda\envs\python3.8\lib\site-packages\statsmodels\compat\scipy.py:6: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SP_VERSION = LooseVersion(scipy.__version__)
C:\Users\wyd_h\.conda\envs\python3.8\lib\site-packages\statsmodels\compat\scipy.py:7: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SCIPY_11 = SP_VERSION < LooseVersion("1.2.0")
C:\Users\wyd_h\.conda\envs\python3.8\lib\site-packages\statsmodels\compat\scipy.py:10: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SCIPY_GT_14 = SP_VERSION >= LooseVersion("1.5")
C:\Users\wyd_h\.conda\envs\python3.8\lib\site-packages\statsmodels\compat\scipy.py:11: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SP_LT_15 = SP_VERSION < LooseVersion("1.5")
C:\Users\wyd_h\.conda\envs\python3.8\lib\site-packages\statsmodels\compat\numpy.py:46: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  NP_LT_114 = LooseVersion(np.__version__) < LooseVersion('1.14')

**Comment by Sunting78** [comment]
您好 给下具体的执行命令

**Comment by Sunting78** [comment]
您好，distutils是Python的一个旧的包和模块分发工具，已经被认为是不再维护的，并且在其最新版本中已经标记为弃用。推荐使用packaging库作为替代。
