### ISSUE TITLE
ubuntu 18 + python3.10.10 , pip install paddlets 失败！！！

### ISSUE THREAD

**Issue by david-95** [PaddlePaddle/PaddleTS#463]
Collecting statsmodels<=0.12.2,>=0.10.2
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/10/26/0fd61f95667e56fd597ecca715dff3623ed1122b6f895ed2b4dfb54afc04/statsmodels-0.12.2.tar.gz (17.5 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [3592 lines of output]
      Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
      Ignoring numpy: markers 'python_version == "3.6"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7"' don't match your environment
      Collecting setuptools
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/bb/26/7945080113158354380a12ce26873dd6c1ebd88d47f5bc24e2c5bb38c16a/setuptools-68.2.2-py3-none-any.whl (807 kB)
      Collecting wheel
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/fa/7f/4c07234086edbce4a0a446209dc0cb08a19bb206a3ea53b2f56a403f983b/wheel-0.41.3-py3-none-any.whl (65 kB)
      Collecting cython>=0.29.14
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/db/33/7fb241cdb3499078fbd3b0e5f87af1a3114a437e6b75bce80cd2f644cc5a/Cython-3.0.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
      Collecting numpy==1.17.5
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d9/09/8e89c05abc450ea347f40b4fa917ec5c69b5228da344487f178586a3187c/numpy-1.17.5.zip (6.4 MB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting scipy>=1.2
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/18/44/7e8d208eb59a8224fcc474415104f13be9b378be8da63f76dfde12ec2b44/scipy-1.11.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (36.4 MB)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/a8/cc/c36f3439f5d47c3b13833ce6687b43a040cc7638c502ac46b41e2d4f3d6f/scipy-1.11.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (36.3 MB)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/14/f2/10fa23f0a6b9b2439c01579ae4a9b1849d4822e972515c8f92584bfda5e9/scipy-1.11.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (36.3 MB)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/1f/4b/3bacad9a166350cb2e518cea80ab891016933cc1653f15c90279512c5fa9/scipy-1.10.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.4 MB)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/76/22/287d06df9b359ba6df3f986e83267f240132379e4181c43cead3c5d41227/scipy-1.10.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.4 MB)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/59/0b/8a9acfc5c36bbf6e18d02f3a08db5b83bebba510be2df3230f53852c74a4/scipy-1.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.7 MB)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/e9/05/3ce7e813ee0666fc10ede875da17d8d5671b774491dcfb4be176c3a880e2/scipy-1.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.7 MB)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c2/89/37b6e11bfe24e96a375fc39e6ffb6c2f27ff795cfb735ae83130e0bf78b5/scipy-1.9.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (43.9 MB)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/e7/cc/82a1ce76bb5b6177fdd5d0f98e2953436abcdfdaa4412d45b54e75821bad/scipy-1.9.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (43.9 MB)
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/bc/fe/72b611ba221c3367b06163992af4807515d6e0e09b3b9beee8ec22162d6f/scipy-1.8.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (42.2 MB)
      Building wheels for collected packages: numpy
        Building wheel for numpy (setup.py): started
        Building wheel for numpy (setup.py): finished with status 'error'
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [3082 lines of output]
            Running from numpy source directory.
            blas_opt_info:
            blas_mkl_info:
            customize UnixCCompiler
              FOUND:
                libraries = ['mkl_rt', 'pthread']
                library_dirs = ['/home/grow/anaconda3/envs/diffusionenv/lib']
                define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
                include_dirs = ['/usr/local/include', '/usr/include', '/home/grow/anaconda3/envs/diffusionenv/include']
      
              FOUND:
                libraries = ['mkl_rt', 'pthread']
                library_dirs = ['/home/grow/anaconda3/envs/diffusionenv/lib']
                define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
                include_dirs = ['/usr/local/include', '/usr/include', '/home/grow/anaconda3/envs/diffusionenv/include']
      
            /bin/sh: 1: svnversion: not found
            non-existing path in 'numpy/distutils': 'site.cfg'
            lapack_opt_info:
            lapack_mkl_info:
            customize UnixCCompiler
              FOUND:
                libraries = ['mkl_rt', 'pthread']
                library_dirs = ['/home/grow/anaconda3/envs/diffusionenv/lib']
                define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
                include_dirs = ['/usr/local/include', '/usr/include', '/home/grow/anaconda3/envs/diffusionenv/include']
      
              FOUND:
                libraries = ['mkl_rt', 'pthread']
                library_dirs = ['/home/grow/anaconda3/envs/diffusionenv/lib']
                define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
                include_dirs = ['/usr/local/include', '/usr/include', '/home/grow/anaconda3/envs/diffusionenv/include']
      
            /home/grow/anaconda3/envs/diffusionenv/lib/python3.10/site-packages/setuptools/_distutils/dist.py:265: UserWarning: Unknown distribution option: 'define_macros'
              warnings.warn(msg)
            running bdist_wheel
            running build
            running config_cc
            unifing config_cc, config, build_clib, build_ext, build commands --compiler options
            running config_fc
            unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
            running build_src
            build_src
            building py_modules sources
            creating build
            creating build/src.linux-x86_64-3.1
            creating build/src.linux-x86_64-3.1/numpy
            creating build/src.linux-x86_64-3.1/numpy/distutils
            building library "npymath" sources
            get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
            customize Gnu95FCompiler
            Could not locate executable gfortran
            Could not locate executable f95
            customize IntelFCompiler
            Could not locate executable ifort
            Could not locate executable ifc
            customize LaheyFCompiler
            Could not locate executable lf95
            customize PGroupFCompiler
            Could not locate executable pgfortran
            customize AbsoftFCompiler
            Could not locate executable f90
            Could not locate executable f77
            customize NAGFCompiler
            customize VastFCompiler
            customize CompaqFCompiler
            Could not locate executable fort
            customize IntelItaniumFCompiler
            Could not locate executable efort
            Could not locate executable efc
            customize IntelEM64TFCompiler
            customize GnuFCompiler
            Could not locate executable g77
            customize G95FCompiler
            Could not locate executable g95
            customize PathScaleFCompiler
            Could not locate executable pathf95
            customize NAGFORCompiler
            Could not locate executable nagfor
            don't know how to compile Fortran code on platform 'posix'
            C compiler: gcc -pthread -B /home/grow/anaconda3/envs/diffusionenv/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC
      
            compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/grow/anaconda3/envs/diffusionenv/include/python3.10 -c'
            gcc: _configtest.c
            gcc -pthread -B /home/grow/anaconda3/envs/diffusionenv/compiler_compat _configtest.o -o _configtest
            success!
            removing: _configtest.c _configtest.o _configtest.o.d _configtest
            C compiler: gcc -pthread -B /home/grow/anaconda3/envs/diffusionenv/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC
      
            compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/grow/anaconda3/envs/diffusionenv/include/python3.10 -c'
            gcc: _configtest.c
            _configtest.c:1:5: warning: conflicting types for built-in function ‘exp’ [-Wbuiltin-declaration-mismatch]
             int exp (void);
                 ^~~
            gcc -pthread -B /home/grow/anaconda3/envs/diffusionenv/compiler_compat _configtest.o -o _configtest
            /home/grow/anaconda3/envs/diffusionenv/compiler_compat/ld: _configtest.o: in function `main':
            _configtest.c:(.text.startup+0x5): undefined reference to `exp'
            collect2: error: ld returned 1 exit status
            failure.
            removing: _configtest.c _configtest.o _configtest.o.d
            C compiler: gcc -pthread -B /home/grow/anaconda3/envs/diffusionenv/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC
      
            compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/grow/anaconda3/envs/diffusionenv/include/python3.10 -c'
            gcc: _configtest.c
            _configtest.c:1:5: warning: conflicting types for built-in function ‘exp’ [-Wbuiltin-declaration-mismatch]
             int exp (void);
                 ^~~
            gcc -pthread -B /home/grow/anaconda3/envs/diffusionenv/compiler_compat _configtest.o -lm -o _configtest
            success!
            removing: _configtest.c _configtest.o _configtest.o.d _configtest
            creating build/src.linux-x86_64-3.1/numpy/core
            creating build/src.linux-x86_64-3.1/numpy/core/src
            creating build/src.linux-x86_64-3.1/numpy/core/src/npymath
            conv_template:> build/src.linux-x86_64-3.1/numpy/core/src/npymath/npy_math_internal.h
              adding 'build/src.linux-x86_64-3.1/numpy/core/src/npymath' to include_dirs.
            conv_template:> build/src.linux-x86_64-3.1/numpy/core/src/npymath/ieee754.c
            conv_template:> build/src.linux-x86_64-3.1/numpy/core/src/npymath/npy_math_complex.c
            None - nothing done with h_files = ['build/src.linux-x86_64-3.1/numpy/core/src/npymath/npy_math_internal.h']
            building library "npysort" sources
            creating build/src.linux-x86_64-3.1/numpy/core/src/common
            conv_template:> build/src.linux-x86_64-3.1/numpy/core/src/common/npy_sort.h
              adding 'build/src.linux-x86_64-3.1/numpy/core/src/common' to include_dirs.
            creating build/src.linux-x86_64-3.1/numpy/core/src/npysort
            conv_template:> build/src.linux-x86_64-3.1/numpy/core/src/npysort/quicksort.c
            conv_template:> build/src.linux-x86_64-3.1/numpy/core/src/npysort/mergesort.c
            conv_template:> build/src.linux-x86_64-3.1/numpy/core/src/npysort/timsort.c
            conv_template:> build/src.linux-x86_64-3.1/numpy/core/src/npysort/heapsort.c
            conv_template:> build/src.linux-x86_64-3.1/numpy/core/src/npysort/radixsort.c
            conv_template:> build/src.linux-x86_64-3.1/numpy/core/src/common/npy_partition.h
            conv_template:> build/src.linux-x86_64-3.1/numpy/core/src/npysort/selection.c
            conv_template:> build/src.linux-x86_64-3.1/numpy/core/src/common/npy_binsearch.h
            conv_template:> build/src.linux-x86_64-3.1/numpy/core/src/npysort/binsearch.c
            None - nothing done with h_files = ['build/src.linux-x86_64-3.1/numpy/core/src/common/npy_sort.h', 'build/src.linux-x86_64-3.1/numpy/core/src/common/npy_partition.h', 'build/src.linux-x86_64-3.1/numpy/core/src/common/npy_binsearch.h']
            building extension "numpy.core._dummy" sources
            Generating build/src.linux-x86_64-3.1/numpy/core/include/numpy/config.h
            C compiler: gcc -pthread -B /home/grow/anaconda3/envs/diffusionenv/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC
      
            compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/grow/anaconda3/envs/diffusionenv/include/python3.10 -c'
            gcc: _configtest.c
            success!
            removing: _configtest.c _configtest.o _configtest.o.d
            C compiler: gcc -pthread -B /home/grow/anaconda3/envs/diffusionenv/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC
      
            compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/grow/anaconda3/envs/diffusionenv/include/python3.10 -c'
            gcc: _configtest.c
            success!
            removing: _configtest.c _configtest.o _configtest.o.d
            C compiler: gcc -pthread -B /home/grow/anaconda3/envs/diffusionenv/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC
      
            compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/grow/anaconda3/envs/diffusionenv/include/python3.10 -c'
            gcc: _configtest.c
            _configtest.c:1:10: fatal error: sys/endian.h: No such file or directory
             #include <sys/endian.h>
                      ^~~~~~~~~~~~~~
            compilation terminated.
            failure.
            removing: _configtest.c _configtest.o
            C compiler: gcc -pthread -B /home/grow/anaconda3/envs/diffusionenv/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC
      
            compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/grow/anaconda3/envs/diffusionenv/include/python3.10 -c'
            gcc: _configtest.c
            success!
            removing: _configtest.c _configtest.o _configtest.o.d
            C compiler: gcc -pthread -B /home/grow/anaconda3/envs/diffusionenv/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC
      
            compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/grow/anaconda3/envs/diffusionenv/include/python3.10 -c'
            gcc: _configtest.c
            success!
            removing: _configtest.c _configtest.o _configtest.o.d
            C compiler: gcc -pthread -B /home/grow/anaconda3/envs/diffusionenv/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC
      
            compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/grow/anaconda3/envs/diffusionenv/include/python3.10 -c'
            gcc: _configtest.c
            success!
            removing: _configtest.c _configtest.o _configtest.o.d
            C compiler: gcc -pthread -B /home/grow/anaconda3/envs/diffusionenv/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC
      
            compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/grow/anaconda3/envs/diffusionenv/include/python3.10 -c'
            gcc: _configtest.c
            success!
            removing: _configtest.c _configtest.o _configtest.o.d
            C compiler: gcc -pthread -B /home/grow/anaconda3/envs/diffusionenv/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC
      
            compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/grow/anaconda3/envs/diffusionenv/include/python3.10 -c'
            gcc: _configtest.c
            _configtest.c: In function ‘main’:
            _configtest.c:5:16: warning: variable ‘test_array’ set but not used [-Wunused-but-set-variable]
                 static int test_array [1 - 2 * !(((long) (sizeof (npy_check_sizeof_type))) >= 0)];
                            ^~~~~~~~~~
            removing: _configtest.c _configtest.o _configtest.o.d
            C compiler: gcc -pthread -B /home/grow/anaconda3/envs/diffusionenv/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC
      
            compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/grow/anaconda3/envs/diffusionenv/include/python3.10 -c'
            gcc: _configtest.c
            _configtest.c: In function ‘main’:
            _configtest.c:5:16: warning: variable ‘test_array’ set but not used [-Wunused-but-set-variable]
                 static int test_array [1 - 2 * !(((long) (sizeof (npy_check_sizeof_type))) == 4)];
                            ^~~~~~~~~~
            removing: _configtest.c _configtest.o _configtest.o.d
            C compiler: gcc -pthread -B /home/grow/anaconda3/envs/diffusionenv/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC
      
            compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/grow/anaconda3/envs/diffusionenv/include/python3.10 -c'
            gcc: _configtest.c
            _configtest.c: In function ‘main’:
            _configtest.c:5:16: warning: variable ‘test_array’ set but not used [-Wunused-but-set-variable]
                 static int test_array [1 - 2 * !(((long) (sizeof (npy_check_sizeof_type))) >= 0)];
                            ^~~~~~~~~~
            removing: _configtest.c _configtest.o _configtest.o.d
            C compiler: gcc -pthread -B /home/grow/anaconda3/envs/diffusionenv/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC
      
            compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/grow/anaconda3/envs/diffusionenv/include/python3.10 -c'
            gcc: _configtest.c
            _configtest.c: In function ‘main’:
            _configtest.c:5:16: warning: variable ‘test_array’ set but not used [-Wunused-but-set-variable]
                 static int test_array [1 - 2 * !(((long) (sizeof (npy_check_sizeof_type))) == 8)];
                            ^~~~~~~~~~
            removing: _configtest.c _configtest.o _configtest.o.d
            C compiler: gcc -pthread -B /home/grow/anaconda3/envs/diffusionenv/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC
      
            compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/grow/anaconda3/envs/diffusionenv/include/python3.10 -c'
            gcc: _configtest.c
            success!
            removing: _configtest.c _configtest.o _configtest.o.d
            C compiler: gcc -pthread -B /home/grow/anaconda3/envs/diffusionenv/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC
      
            compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/grow/anaconda3/envs/diffusionenv/include/python3.10 -c'
            gcc: _configtest.c
            _configtest.c: In function ‘main’:
            _configtest.c:5:16: warning: variable ‘test_array’ set but not used [-Wunused-but-set-variable]
                 static int test_array [1 - 2 * !(((long) (sizeof (npy_check_sizeof_type))) >= 0)];
                            ^~~~~~~~~~
            removing: _configtest.c _configtest.o _configtest.o.d
            C compiler: gcc -pthread -B /home/grow/anaconda3/envs/diffusionenv/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC
      
            compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/grow/anaconda3/envs/diffusionenv/include/python3.10 -c'
            gcc: _configtest.c
            _configtest.c: In function ‘main’:
            _configtest.c:5:16: warning: variable ‘test_array’ set but not used [-Wunused-but-set-variable]
                 static int test_array [1 - 2 * !(((long) (sizeof (npy_check_sizeof_type))) == 8)];
                            ^~~~~~~~~~
            removing: _configtest.c _configtest.o _configtest.o.d
            C compiler: gcc -pthread -B /home/grow/anaconda3/envs/diffusionenv/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC -O2 -isystem /home/grow/anaconda3/envs/diffusionenv/include -fPIC
      
            compile options: '-Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/grow/anaconda3/envs/diffusionenv/include/python3.10 -c'
            gcc: _configtest.c
            _configtest.c: In function ‘main’:
            _configtest.c:5:16: warning: variable ‘test_array’ set but not used [-Wunused-but-set-variable]
                 static int test_array [1 - 2 * !(((long) (sizeof (npy_check_sizeof_type))) >= 0)];
                            ^~~~~~~~~~
。。。。。

**Comment by Sunting78** [comment]
您好，请您给下具体环境，paddle版本等

**Comment by tinycen** [comment]
我是在aistudio里面运行的，安装的时候也出现了这样的问题！
