### ISSUE TITLE
无法安装PaddleTS库

### ISSUE THREAD

**Issue by fireinwind** [PaddlePaddle/PaddleTS#465]
报错如下:
            gcc: numpy/core/src/common/ufunc_override.c
            gcc: numpy/core/src/common/numpyos.c
            gcc: numpy/core/src/umath/cpuid.c
            gcc: numpy/core/src/umath/ufunc_type_resolution.c
            gcc: numpy/core/src/umath/override.c
            gcc: numpy/core/src/multiarray/mapping.c
            gcc: numpy/core/src/multiarray/methods.c
            gcc: build/src.linux-x86_64-3.1/numpy/core/src/umath/matmul.c
            gcc: build/src.linux-x86_64-3.1/numpy/core/src/umath/clip.c
            error: Command "gcc -pthread -B /opt/conda/envs/python35-paddle120-env/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/conda/envs/python35-paddle120-env/include -fPIC -O2 -isystem /opt/conda/envs/python35-paddle120-env/include -fPIC -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Ibuild/src.linux-x86_64-3.1/numpy/core/src/umath -Ibuild/src.linux-x86_64-3.1/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.1/numpy/core/src/common -Inumpy/core/include -Ibuild/src.linux-x86_64-3.1/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/opt/conda/envs/python35-paddle120-env/include/python3.10 -Ibuild/src.linux-x86_64-3.1/numpy/core/src/common -Ibuild/src.linux-x86_64-3.1/numpy/core/src/npymath -Ibuild/src.linux-x86_64
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
        Running setup.py clean for numpy
        error: subprocess-exited-with-error
      
        × python setup.py clean did not run successfully.
        │ exit code: 1
        ╰─> [10 lines of output]
            Running from numpy source directory.
           
            `setup.py clean` is not supported, use one of the following instead:
           
              - `git clean -xdf` (cleans all files)
              - `git clean -Xdf` (cleans all versioned files, doesn't touch
                                  files that aren't checked into the git repo)
           
            Add `--force` to your command to use it anyway if you must (unsupported).
           
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed cleaning build dir for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Note: you may need to restart the kernel to use updated packages.

看提示是numpy的问题,但是实际上感觉不是numpy的问题,单独安装numpy也不行.大部分的环境都测试了.还是有问题,包括mac, linux下的3.8.13的python和3.10的python, 包括AI Studio上的GPU和CPU环境都不行,看了一下python的版本是3.10.10,paddle的cpu和gpu版本都是2.5.2

**Comment by allentern** [comment]
个人经验：新建虚拟环境，选python3.9，按照说明安装，win11、centos7都OK，装过很多遍了，都OK。

**Comment by rsj123** [comment]
aistudio上面把paddle降级到2.3.2就能用了

**Comment by Sunting78** [comment]
可以给下具体的安装环境

**Comment by fireinwind** [comment]
> 可以给下具体的安装环境

问题的最后就是啊,或者方便给一个ai studio的通过的环境就行.我是不理解为什么ai studio都不行.当前版本发布的时候,不在ai studio测试么?

**Comment by tinycen** [comment]
> aistudio上面把paddle降级到2.3.2就能用了

已验证，降级后可以安装。
