### ISSUE TITLE
paddlets的模型怎么通过named_layers获取神经网络的层呢

### ISSUE THREAD

**Issue by Laurazlj** [PaddlePaddle/PaddleTS#466]
paddlets的模型怎么通过named_layers获取神经网络的层呢，直接用named_layers函数报错没有这个attribute，请问应该用什么呢？

**Comment by Sunting78** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/summary_en.html
看下summary这个接口能满足要求吗？

**Comment by Laurazlj** [comment]
> https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/summary_en.html 看下summary这个接口能满足要求吗？

我之前用这个接口，针对时序预测模型，input的size总是报错，不知道应该是什么。例如mlpregressor，input的size应该是多少呢？此外，我需要针对特定的layer加hook，这个接口可能不行，只能打印出模型结构。

**Comment by Sunting78** [comment]
您好，input应是forward函数的输入tensor的shape

**Comment by Laurazlj** [comment]
> 您好，input应是forward函数的输入tensor的shape

您好，试了一下报错如下：
File "train.py", line 38, in <module>
    paddle.summary(model,(1,1,24,28))
  File "/data/miniconda3/envs/mstest/lib/python3.8/site-packages/paddle/hapi/model_summary.py", line 187, in summary
    in_train_mode = net.training
AttributeError: 'TransformerModel' object has no attribute 'training'

**Comment by Sunting78** [comment]
您好，由于问题超过一周，将自动关闭。若有问题可以重新打开，或者重新提issue。感谢理解。
