### ISSUE TITLE
XAI模块是不可以分析static_cov的么

### ISSUE THREAD

**Issue by IgnoranceSmile** [PaddlePaddle/PaddleTS#474]
代码：
se = ShapExplainer(model, train_data)
shap_value = se.explain(train_data, nsamples=100)
se.summary_plot(out_chunk_indice=1, sample_index=0)
报错：
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_79237/4214853139.py in <module>
----> 1 se.summary_plot(out_chunk_indice=1, sample_index=0)

/usr/local/lib/python3.7/dist-packages/paddlets/xai/post_hoc/shap_explainer.py in summary_plot(self, out_chunk_indice, sample_index, **kwargs)
    407             for j in range(self.shap_value.shape[3]):
    408                 feature_names.append('%s:%s_lag_%d' % (self.unique_cols[j], 
--> 409                                                        self.key_feature[self.unique_cols[j]].split('_')[0],
    410                                                        i - self._in_chunk_len + 1))
    411         if self.shap_method == 'kernel':

KeyError: 'static_cov'

**Comment by a31413510** [comment]
是的，目前static_cov是没有支持的

**Comment by Sunting78** [comment]
您好，超过一个月该issue已关闭，如有疑问可以reopen或新提issue~
