### ISSUE TITLE
如何保存模型，并能够使用保存的模型进行推理？

### ISSUE THREAD

**Issue by Wenqianqian123** [PaddlePaddle/PaddleTS#478]
运行train.py脚本可执行训练，请问如何保存训练后的模型，并在新的脚本中，使用训练好的模型进行推理，比如使用configs.longterm_forecast下的Crossformer_ECL.yaml配置文件，执行train.py。

**Comment by Sunting78** [comment]
您好，请查看使用文档：https://paddlets.readthedocs.io/zh-cn/latest/source/modules/models/overview.html
# 7 save the model
model.save("/path/to/save/modelname")

# 8 load the model
loaded_model = load("/path/to/save/modelname")

**Comment by TingquanGao** [comment]
该issue已关闭，如有疑问可以reopen或新提issue~
