### ISSUE TITLE
PaddleTS多时序数据导入怎么获取group_id

### ISSUE THREAD

**Issue by kachadx** [PaddlePaddle/PaddleTS#479]
#Load TSDatasets by group_id
from paddlets import TSDataset
tsdatasets = TSDataset.load_from_dataframe(
    df=sample,
    group_id='id',
    target_cols='a',
    observed_cov_cols=['c', 'd'],
    #static_cov_cols='id'
)
使用group_id导入数据，得到的是个TSDataset集合，怎么知道每个集和对应的group_id值是多少，没找到对应的方法和属性，而且预测后也不知道对应的是哪个group_id的预测值

**Comment by kachadx** [comment]
对于多时序数据的回测支持好像也不是很好，需要循环去回测吗？也没有一个整体的一个指标对应多时序数据

**Comment by Sunting78** [comment]
您好，len(tsdatasets)的长度就是group一共有多少组。指定group_id后 会读取成list，相同的group_id被划分为一组。

**Comment by kachadx** [comment]
指定group_id？怎么指定group_id,没找到对应的方法和属性

**Comment by Sunting78** [comment]
在您的csv数据中，哪一个是表示group_id的，就设置group_id='xx'即可

**Comment by Sunting78** [comment]
您好，由于问题超过一周，将自动关闭。
