### ISSUE TITLE
如果不需要填充呢，因为有些场景本来就是缺数据的，像股票价格存在休盘和节假日的情况，怎么将缺失的两个时间点拼在一起？避免在训练过程中产生错误，比如：

### ISSUE THREAD

**Issue by kachadx** [PaddlePaddle/PaddleTS#481]
如果不需要填充呢，因为有些场景本来就是缺数据的，像股票价格存在休盘和节假日的情况，怎么将缺失的两个时间点拼在一起？避免在训练过程中产生错误，比如：
1.ValueError: The `point` is out of the valid range
2.ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
。

_Originally posted by @Hoogck in https://github.com/PaddlePaddle/PaddleTS/issues/266#issuecomment-1407619481_

**Comment by Sunting78** [comment]
您好，这种情况可以设置freq='B'尝试一下，表示每工作日。如果改方式无法运行，可以通过按照之前几天均值的方式填充。

**Comment by kachadx** [comment]
找到方法了，time_col不要设置，使用默认的RangeIndex，freq=1，这样就不会填充不存在的日期数据了
