### ISSUE TITLE
多输入-单输出的修改方式

### ISSUE THREAD

**Issue by IgnoranceSmile** [PaddlePaddle/PaddleTS#484]
目前很多模型，比如LSTNet等目前都不支持协变量，这些模型有办法实现多时序信息输入然后只有其中一个作为target么？

**Comment by Sunting78** [comment]
您好，这可能涉及您要自行修改网络结构，保证协变量生效。可以参考https://github.com/PaddlePaddle/PaddleTS/blob/a3f275c51a1c6d6803ec2af269c049a29039ae59/paddlets/models/forecasting/dl/Nonstationary.py#L109C9-L109C19

**Comment by Sunting78** [comment]
您好，由于超过一周，问题将关闭。
