### ISSUE TITLE
PaddleTS模型库里面哪些是回归类，哪些可以做分类

### ISSUE THREAD

**Issue by kachadx** [PaddlePaddle/PaddleTS#485]

**Comment by Sunting78** [comment]
您好，直接查看代码比较全面，[models目录按照任务类型进行了区分](https://github.com/PaddlePaddle/PaddleTS/tree/main/paddlets/models)。可以查看每个目录下的__init__.py 文件中的模型，例如分类：https://github.com/PaddlePaddle/PaddleTS/blob/a3f275c51a1c6d6803ec2af269c049a29039ae59/paddlets/models/classify/__init__.py#L7

**Comment by TingquanGao** [comment]
长时间未回复，该issue已关闭，如仍有问题可以reopen或新开issue。
