### ISSUE TITLE
使用LSTNet模型训练时，报错ValueError: Input contains NaN.

### ISSUE THREAD

**Issue by JackLRR** [PaddlePaddle/PaddleTS#486]
使用LSTNet模型训练，有时会报错ValueError: Input contains NaN，有时不会。使用其它模型没有问题，这是什么原因？

**Comment by Sunting78** [comment]
您好，我们排查一下。能给一个出错的数据范例吗？

**Comment by Sunting78** [comment]
您好，由于问题超过一周，将自动关闭。若有问题可以重新打开，或者重新提issue。感谢理解。
