### ISSUE TITLE
TFT方法有办法修改损失函数为MAE、MSE之类的其他函数么

### ISSUE THREAD

**Issue by IgnoranceSmile** [PaddlePaddle/PaddleTS#488]

**Comment by IgnoranceSmile** [comment]
我希望通过修改损失函数的方式，让tft模型支持AutoTS，这可行么

**Comment by Sunting78** [comment]
您好，tft由于是概率预测模型，暂时不支持。可以修改成mse，但可能涉及网络输出层结构变化，可能无法保证效果。

**Comment by Sunting78** [comment]
您好，由于问题超过一周，将自动关闭。若有问题可以重新打开，或者重新提issue。感谢理解。
