### ISSUE TITLE
xai的shap分析为什么都是返回0

### ISSUE THREAD

**Issue by kachadx** [PaddlePaddle/PaddleTS#501]
xai的shap分析为什么都是返回0，不管是用kernel还是deep，所有特征都是返回0,
 shap_explainer = ShapExplainer(model, train_t, shap_method="kernel", n_jobs=4)
    shap_values = shap_explainer.explain(test_t, nsamples=100)

**Comment by Sunting78** [comment]
您好，抱歉，xai暂时不再维护。
