### ISSUE TITLE
PaddleTS PatchTST模型是否支持协变量？

### ISSUE THREAD

**Issue by TommysLee** [PaddlePaddle/PaddleTS#514]
PatchTST模型是否支持协变量，如：观测协变量、已知未来协变量、静态协变量等。
我拟通过协变量提升时序模型的精度。

若支持，是否通过类似如下方式构建各协变量：
`known_cov_dataset = TSDataset.load_from_dataframe(
    df,
    time_col='time_col',
    known_cov_cols=['known_cov_1', 'known_cov_2'],
    freq='1h'
)`

**Comment by Sunting78** [comment]
PatchTST不支持 构建方法是可以的
