### ISSUE TITLE
在A100服务器使用Paddlepaddle2.6在PaddleTS 套件中训练DLinear_ECL模型，loss降不下去不收敛

### ISSUE THREAD

**Issue by duqimeng** [PaddlePaddle/PaddleTS#522]
1、希望可以提供一下时间序列预测，异常检测，分类所使用的数据集（并非原始数据集，是否可以提供文档中训练出精度所使用的数据集）
2、DLinear_ECL模型，loss降不下去不收敛训练日志如下：
[DLinear_ECL.txt](https://github.com/user-attachments/files/16757074/DLinear_ECL.txt)

**Comment by Sunting78** [comment]
https://github.com/PaddlePaddle/PaddleTS/blob/release_v1.1/docs/model_eval.md 里面有数据和训练配置 可以参考

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
