### ISSUE TITLE
【建议】PPTS训练时 每个step打印一次log，太频繁了，建议降低Log的频率

### ISSUE THREAD

**Issue by TommysLee** [PaddlePaddle/PaddleTS#523]
之前clone的PPTS  每个Epoch打印一次Log  挺好的，也便于查阅log，抓取重要信息。

而现在clone的PPTS项目，每个step打印一次log，太频繁了，内容太多，找关键日志犹如大海捞针。建议采用之前的log策略。

**Comment by Bobholamovic** [comment]
感谢你的建议！

每个step打印一次log主要是[这个PR](https://github.com/PaddlePaddle/PaddleTS/pull/521)引入的，看起来是为了支持其它功能而改变的行为。如果希望保留之前的行为，目前暂时可能只能使用旧版本的PaddleTS，例如通过如下方式：

```bash
# clone之后执行
git reset 05c2c5f880d2dffa1909ea1cd98bcadcb92f7693
```

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
