### ISSUE TITLE
执行 example中的 anomaly_example 案例，结果不一致

### ISSUE THREAD

**Issue by liuzhipengchd** [PaddlePaddle/PaddleTS#530]
用的是master分支，模型训练完之后的指标都是0，应该怎么解决呀。

系统：mac m1芯片

![WeChatd14e3159d310933d14227f1e4184a33a](https://github.com/user-attachments/assets/8c3cdc99-a6da-4046-819f-d2b16936cfd6)

**Comment by liuzhipengchd** [comment]
@Sunting78 大佬，可以帮忙看一下吗

**Comment by liu-jiaxuan** [comment]
@Sunting78

**Comment by Sunting78** [comment]
您好，是main分枝吗？是直接安装pip install paddlets吗？还是源码安装的呢？

**Comment by liuzhipengchd** [comment]
> 您好，是main分枝吗？是直接安装pip install paddlets吗？还是源码安装的呢？

大佬你好。我用的是release_v1.1 进行安装的。。安装过程是：python setup.py build  ,python setup.py install 



(tf_rosetta) lzp@lzpdeMacBook-Pro PaddleTS % pip list | grep paddlets
paddlets                          1.1.0

**Comment by liu-jiaxuan** [comment]
Hi，main分支中修复了其他分支中的潜在问题，您可以试一下main分支~

**Comment by liuzhipengchd** [comment]
> Hi，main分支中修复了其他分支中的潜在问题，您可以试一下main分支~

好的，应该可以了

**Comment by liu-jiaxuan** [comment]
好的~

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
