### ISSUE TITLE
mac M3 安装失败

### ISSUE THREAD

**Issue by 125793014** [PaddlePaddle/PaddleTS#531]
mac环境pip install paddlets 失败，具体如下：
1、环境：mac M3、conda 24.9.1、python3.9、paddlepaddle==2.6.1
2、报错：
(test) xxxx@bogon test % pip install paddlets                                                                 
Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Collecting paddlets
  Using cached https://mirrors.aliyun.com/pypi/packages/28/3e/ff538c1adf83ce9479c956141ce2dde833e10cb63aa7dea433fbfaff07fa/paddlets-1.1.0-py3-none-any.whl (572 kB)
Collecting numpy<=1.19.5,>=1.17.0 (from paddlets)
  Using cached https://mirrors.aliyun.com/pypi/packages/51/60/3f0fe5b7675a461d96b9d6729beecd3532565743278a9c3fe6dd09697fa7/numpy-1.19.5.zip (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pandas<=1.3.5,>=0.25.0 (from paddlets)
  Using cached pandas-1.3.5-cp39-cp39-macosx_11_0_arm64.whl
Collecting scikit-learn>=0.24.1 (from paddlets)
  Using cached https://mirrors.aliyun.com/pypi/packages/1b/be/386ef63d9d5e2ddf8308f6a164e4b388d5c5aecc0504d25acc6b33d8b09e/scikit_learn-1.5.2-cp39-cp39-macosx_12_0_arm64.whl (11.0 MB)
Collecting chinese-calendar==1.8.0 (from paddlets)
  Using cached https://mirrors.aliyun.com/pypi/packages/d3/8a/feaef2cf0aa05d13dfab540770718467ec348b6e71a700197fbd4224e922/chinese_calendar-1.8.0-py2.py3-none-any.whl (11 kB)
Collecting python-docx (from paddlets)
  Using cached https://mirrors.aliyun.com/pypi/packages/3e/3d/330d9efbdb816d3f60bf2ad92f05e1708e4a1b9abe80461ac3444c83f749/python_docx-1.1.2-py3-none-any.whl (244 kB)
Collecting matplotlib>=3.1.2 (from paddlets)
  Using cached https://mirrors.aliyun.com/pypi/packages/46/87/5f567fda78130a8394f9dcf3accb1b7b0c9baf0384307ef59032f5b1d17c/matplotlib-3.9.2-cp39-cp39-macosx_11_0_arm64.whl (7.8 MB)
Collecting PyWavelets<=1.3.0,>=1.1.0 (from paddlets)
  Using cached https://mirrors.aliyun.com/pypi/packages/7d/d4/2fd75d3d69047fc6eac05b77c3d343b4c2ec9d7c0b8057c53d3bfd964c18/PyWavelets-1.3.0-cp39-cp39-macosx_11_0_arm64.whl (4.3 MB)
Collecting statsmodels<=0.12.2,>=0.10.2 (from paddlets)
  Using cached https://mirrors.aliyun.com/pypi/packages/10/26/0fd61f95667e56fd597ecca715dff3623ed1122b6f895ed2b4dfb54afc04/statsmodels-0.12.2.tar.gz (17.5 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [80 lines of output]
      Looking in indexes: https://mirrors.aliyun.com/pypi/simple
      Ignoring numpy: markers 'python_version == "3.6"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7"' don't match your environment
      Collecting setuptools
        Using cached https://mirrors.aliyun.com/pypi/packages/ff/ae/f19306b5a221f6a436d8f2238d5b80925004093fa3edea59835b514d9057/setuptools-75.1.0-py3-none-any.whl (1.2 MB)
      Collecting wheel
        Using cached https://mirrors.aliyun.com/pypi/packages/1b/d1/9babe2ccaecff775992753d8686970b1e2755d21c8a63be73aba7a4e7d77/wheel-0.44.0-py3-none-any.whl (67 kB)
      Collecting cython>=0.29.14
        Using cached https://mirrors.aliyun.com/pypi/packages/43/39/bdbec9142bc46605b54d674bf158a78b191c2b75be527c6dcf3e6dfe90b8/Cython-3.0.11-py2.py3-none-any.whl (1.2 MB)
      Collecting numpy==1.17.5
        Using cached https://mirrors.aliyun.com/pypi/packages/d9/09/8e89c05abc450ea347f40b4fa917ec5c69b5228da344487f178586a3187c/numpy-1.17.5.zip (6.4 MB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting scipy>=1.2
        Using cached https://mirrors.aliyun.com/pypi/packages/5c/c0/e71b94b20ccf9effb38d7147c0064c08c622309fd487b1b677771a97d18c/scipy-1.13.1-cp39-cp39-macosx_12_0_arm64.whl (30.3 MB)
      INFO: pip is looking at multiple versions of scipy to determine which version is compatible with other requirements. This could take a while.
        Using cached https://mirrors.aliyun.com/pypi/packages/b2/33/cd6ae14e861e3f1ea1440c62bd3d16cc3654d77d79666f348ad0176afde8/scipy-1.13.0-cp39-cp39-macosx_12_0_arm64.whl (30.3 MB)
        Using cached https://mirrors.aliyun.com/pypi/packages/32/48/f605bad3e610efe05a51b56698578f7a98f900513a4bad2c9f12df845cd6/scipy-1.12.0-cp39-cp39-macosx_12_0_arm64.whl (31.4 MB)
        Using cached https://mirrors.aliyun.com/pypi/packages/d1/3a/0ab839bb67043ab35e5dcf8b611ca9e08e5a8933b0bc7506eedcec664aae/scipy-1.11.4-cp39-cp39-macosx_12_0_arm64.whl (29.7 MB)
        Using cached https://mirrors.aliyun.com/pypi/packages/6f/d9/d10111b008fabab4aea0f98274d3f5db4bd33baadf30c782b6e659ec7708/scipy-1.11.3-cp39-cp39-macosx_12_0_arm64.whl (29.7 MB)
        Using cached https://mirrors.aliyun.com/pypi/packages/77/31/b063f21370c6050a663aae5a9868d2fe112b21caeface3c248016dfea092/scipy-1.11.2-cp39-cp39-macosx_12_0_arm64.whl (29.6 MB)
        Using cached https://mirrors.aliyun.com/pypi/packages/d8/97/3a15209262cf523dab38de372ff814f8fb7815f98ccc07c7996e77910612/scipy-1.11.1-cp39-cp39-macosx_12_0_arm64.whl (29.6 MB)
        Using cached https://mirrors.aliyun.com/pypi/packages/e7/f0/55d81813b1a4cb79ce7dc8290eac083bf38bfb36e1ada94ea13b7b1a5f79/scipy-1.10.1-cp39-cp39-macosx_12_0_arm64.whl (28.9 MB)
      INFO: pip is still looking at multiple versions of scipy to determine which version is compatible with other requirements. This could take a while.
        Using cached https://mirrors.aliyun.com/pypi/packages/2b/54/7536dbfcbea26ca2c11d3c55b0c2d806d4349b5852318e12b98ffee27bd8/scipy-1.10.0-cp39-cp39-macosx_12_0_arm64.whl (28.9 MB)
        Using cached https://mirrors.aliyun.com/pypi/packages/c8/0f/d9f8c50be8670b7ba6f002679e84cd18f46a23faf62c1590f4d1bbec0c8c/scipy-1.9.3-cp39-cp39-macosx_12_0_arm64.whl (28.6 MB)
        Using cached https://mirrors.aliyun.com/pypi/packages/ec/7b/bf1cb24ba269d5911ba723a17e4c10f64c727798d74be0ac87c5fd9201ca/scipy-1.9.2-cp39-cp39-macosx_12_0_arm64.whl (28.6 MB)
        Using cached https://mirrors.aliyun.com/pypi/packages/fe/de/caec3ae06f5380b8c91518f119f9b113a2da0619f7d8d8937b8ee517a29e/scipy-1.9.1-cp39-cp39-macosx_12_0_arm64.whl (29.9 MB)
        Using cached https://mirrors.aliyun.com/pypi/packages/37/c6/eeecc4c9699605ed4bd00cce6c7cf945f5eb7aa3b3ae9f8f6aeadbb0a59b/scipy-1.9.0-cp39-cp39-macosx_12_0_arm64.whl (29.9 MB)
      INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
        Using cached https://mirrors.aliyun.com/pypi/packages/66/d0/faf1d69525836cd4b6a51407b39836f77de266777d073ce5698b3a5244e3/scipy-1.8.1-cp39-cp39-macosx_12_0_arm64.whl (28.7 MB)
      Building wheels for collected packages: numpy
        Building wheel for numpy (setup.py): started
        Building wheel for numpy (setup.py): finished with status 'error'
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [15 lines of output]
            Running from numpy source directory.
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/private/var/folders/qn/nywglnps1fdg9k6physbwgg40000gn/T/pip-install-wx3ynzx1/numpy_5bddbd2d87144ec18f9aa3ee8de1048d/setup.py", line 444, in <module>
                setup_package()
              File "/private/var/folders/qn/nywglnps1fdg9k6physbwgg40000gn/T/pip-install-wx3ynzx1/numpy_5bddbd2d87144ec18f9aa3ee8de1048d/setup.py", line 423, in setup_package
                from numpy.distutils.core import setup
              File "/private/var/folders/qn/nywglnps1fdg9k6physbwgg40000gn/T/pip-install-wx3ynzx1/numpy_5bddbd2d87144ec18f9aa3ee8de1048d/numpy/distutils/core.py", line 26, in <module>
                from numpy.distutils.command import config, config_compiler, \
              File "/private/var/folders/qn/nywglnps1fdg9k6physbwgg40000gn/T/pip-install-wx3ynzx1/numpy_5bddbd2d87144ec18f9aa3ee8de1048d/numpy/distutils/command/config.py", line 20, in <module>
                from numpy.distutils.mingw32ccompiler import generate_manifest
              File "/private/var/folders/qn/nywglnps1fdg9k6physbwgg40000gn/T/pip-install-wx3ynzx1/numpy_5bddbd2d87144ec18f9aa3ee8de1048d/numpy/distutils/mingw32ccompiler.py", line 34, in <module>
                from distutils.msvccompiler import get_build_version as get_build_msvc_version
            ModuleNotFoundError: No module named 'distutils.msvccompiler'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
        Running setup.py clean for numpy
        error: subprocess-exited-with-error
      
        × python setup.py clean did not run successfully.
        │ exit code: 1
        ╰─> [10 lines of output]
            Running from numpy source directory.
      
            `setup.py clean` is not supported, use one of the following instead:
      
              - `git clean -xdf` (cleans all files)
              - `git clean -Xdf` (cleans all versioned files, doesn't touch
                                  files that aren't checked into the git repo)
      
            Add `--force` to your command to use it anyway if you must (unsupported).
      
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed cleaning build dir for numpy
      Failed to build numpy
      ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (numpy)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by 125793014** [comment]
是不是 core.txt 里面的 numpy>=1.17.0, <=1.19.5  升级到 numpy>=1.17.0, <=1.24.4？

**Comment by Sunting78** [comment]
M3芯片未适配过，这个问题可以尝试下conda install "setuptools <65"之后在安装paddlets ，或者直接拉取paddlets代码，从源码安装paddlets而不是用whl包的方式。

**Comment by 125793014** [comment]
> M3芯片未适配过，这个问题可以尝试下conda install "setuptools <65"之后在安装paddlets ，或者直接拉取paddlets代码，从源码安装paddlets而不是用whl包的方式。

1、conda install "setuptools <65"之后在安装paddlets  
      这种验证了，还是不可行。
2、numpy 版本1.24.4 是否可以?  如果可以 是不是这个低版本在M3上不适配的问题。
       是不是 core.txt 里面的 numpy>=1.17.0, <=1.19.5 升级到 numpy>=1.17.0, <=1.24.4？

**Comment by Sunting78** [comment]
可以尝试一下吧M3芯片未适配过。也可以源码安装，去掉版本限制试一下

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
